// Espacios físicos extraídos del archivo Excel v3.0 (hoja Asignaciones)
// Generado automáticamente — no editar manualmente
const ESPACIOS = [
  {cat:"auditorio",ed:"CAMPUS",cod:"AUDITORIO",piso:"1",nom:"Auditorio Marvel Moreno",ev:"ANA KARINA QUINTERO ARTEAGA"},
  {cat:"auditorio",ed:"CAMPUS",cod:"SAL_PROYECCION",piso:"1",nom:"Salón Gabriel García Márquez",ev:"DANIEL EDUARDO GUTIERREZ BORRERO"},
  {cat:"salon",ed:"BLOI1",cod:"I1-22",piso:"2",nom:"Salón I1-22",ev:"Hailyn Kelly Mejia Piedris"},
  {cat:"salon",ed:"BLOI1",cod:"I1-26",piso:"2",nom:"Salón I1-26",ev:"Hailyn Kelly Mejia Piedris"},
  {cat:"salon",ed:"BLOI1",cod:"I1-23",piso:"2",nom:"Salón I1-23",ev:"Hailyn Kelly Mejia Piedris"},
  {cat:"salon",ed:"BLOI1",cod:"I1-24",piso:"2",nom:"Salón I1-24",ev:"Hailyn Kelly Mejia Piedris"},
  {cat:"salon",ed:"BLOI1",cod:"I1-27",piso:"2",nom:"Salón I1-27",ev:"Hailyn Kelly Mejia Piedris"},
  {cat:"salon",ed:"BLOI1",cod:"I1-25",piso:"2",nom:"Salón I1-25",ev:"Hailyn Kelly Mejia Piedris"},
  {cat:"salon",ed:"BLOI1",cod:"I1-21",piso:"2",nom:"Salón I1-21",ev:"Hailyn Kelly Mejia Piedris"},
  {cat:"salon",ed:"BLOI2",cod:"I2-24",piso:"2",nom:"Salón I2-24",ev:"YOSIRIS YOHANA YEPES MIRANDA"},
  {cat:"salon",ed:"BLOI2",cod:"I2-12",piso:"1",nom:"Salón I2-12",ev:"YOSIRIS YOHANA YEPES MIRANDA"},
  {cat:"salon",ed:"BLOI2",cod:"I2-23",piso:"2",nom:"Salón I2-23",ev:"YOSIRIS YOHANA YEPES MIRANDA"},
  {cat:"salon",ed:"BLOI2",cod:"I2-15",piso:"1",nom:"Salón I2-15",ev:"YOSIRIS YOHANA YEPES MIRANDA"},
  {cat:"salon",ed:"BLOI2",cod:"I2-21",piso:"2",nom:"Salón I2-21",ev:"YOSIRIS YOHANA YEPES MIRANDA"},
  {cat:"salon",ed:"BLOI2",cod:"I2-11",piso:"1",nom:"Salón I2-11",ev:"YOSIRIS YOHANA YEPES MIRANDA"},
  {cat:"salon",ed:"BLOI2",cod:"I2-22",piso:"2",nom:"Salón I2-22",ev:"YOSIRIS YOHANA YEPES MIRANDA"},
  {cat:"salon",ed:"BLOI2",cod:"I2-13",piso:"1",nom:"Salón I2-13",ev:"YOSIRIS YOHANA YEPES MIRANDA"},
  {cat:"salon",ed:"BLOI2",cod:"I2-25",piso:"2",nom:"Salón I2-25",ev:"YOSIRIS YOHANA YEPES MIRANDA"},
  {cat:"salon",ed:"BLOI2",cod:"I2-14",piso:"1",nom:"Salón I2-14",ev:"YOSIRIS YOHANA YEPES MIRANDA"},
  {cat:"salon",ed:"BLOI3",cod:"I3-11",piso:"1",nom:"Salón I3-11",ev:"SANDRA PAOLA PEÑA CASTELLANO"},
  {cat:"salon",ed:"BLOI3",cod:"I3-13",piso:"1",nom:"Salón I3-13",ev:"SANDRA PAOLA PEÑA CASTELLANO"},
  {cat:"salon",ed:"BLOI3",cod:"I3-12",piso:"1",nom:"Salón I3-12",ev:"SANDRA PAOLA PEÑA CASTELLANO"},
  {cat:"salon",ed:"BLOI3",cod:"I3-21",piso:"2",nom:"Salón I3-21",ev:"YOSIRIS YOHANA YEPES MIRANDA"},
  {cat:"salon",ed:"BLOI3",cod:"I3-24",piso:"2",nom:"Salón I3-24",ev:"YOSIRIS YOHANA YEPES MIRANDA"},
  {cat:"salon",ed:"BLOI3",cod:"I3-23",piso:"2",nom:"Salón I3-23",ev:"YOSIRIS YOHANA YEPES MIRANDA"},
  {cat:"salon",ed:"BLOI3",cod:"I3-22",piso:"2",nom:"Salón I3-22",ev:"YOSIRIS YOHANA YEPES MIRANDA"},
  {cat:"salon",ed:"BLOI4",cod:"I4-12",piso:"1",nom:"Salón I4-12",ev:"EYLEEN GIOBET CASTILLO MENDOZA"},
  {cat:"salon",ed:"BLOI4",cod:"I4-25",piso:"2",nom:"Salón I4-25",ev:"EYLEEN GIOBET CASTILLO MENDOZA"},
  {cat:"salon",ed:"BLOI4",cod:"I4-13",piso:"1",nom:"Salón I4-13",ev:"EYLEEN GIOBET CASTILLO MENDOZA"},
  {cat:"salon",ed:"BLOI4",cod:"I4-11",piso:"1",nom:"Salón I4-11",ev:"EYLEEN GIOBET CASTILLO MENDOZA"},
  {cat:"salon",ed:"BLOI4",cod:"I4-21",piso:"2",nom:"Salón I4-21",ev:"EYLEEN GIOBET CASTILLO MENDOZA"},
  {cat:"salon",ed:"BLOI4",cod:"I4-15",piso:"1",nom:"Salón I4-15",ev:"EYLEEN GIOBET CASTILLO MENDOZA"},
  {cat:"salon",ed:"BLOI4",cod:"I4-28",piso:"2",nom:"Salón I4-28",ev:"EYLEEN GIOBET CASTILLO MENDOZA"},
  {cat:"salon",ed:"BLOI4",cod:"I4-22",piso:"2",nom:"Salón I4-22",ev:"EYLEEN GIOBET CASTILLO MENDOZA"},
  {cat:"salon",ed:"BLOI4",cod:"I4-14",piso:"1",nom:"Salón I4-14",ev:"EYLEEN GIOBET CASTILLO MENDOZA"},
  {cat:"salon",ed:"BLOI4",cod:"I4-23",piso:"2",nom:"Salón I4-23",ev:"EYLEEN GIOBET CASTILLO MENDOZA"},
  {cat:"salon",ed:"BLOI4",cod:"I4-27",piso:"2",nom:"Salón I4-27",ev:"EYLEEN GIOBET CASTILLO MENDOZA"},
  {cat:"salon",ed:"BLOI4",cod:"I4-26",piso:"2",nom:"Salón I4-26",ev:"EYLEEN GIOBET CASTILLO MENDOZA"},
  {cat:"salon",ed:"BLOI4",cod:"I4-24",piso:"2",nom:"Salón I4-24",ev:"EYLEEN GIOBET CASTILLO MENDOZA"},
  {cat:"salon",ed:"BLOI4",cod:"I4-S13",piso:"S",nom:"Salón I4-S13",ev:"SANDRA PAOLA PEÑA CASTELLANO"},
  {cat:"salon",ed:"BLOI4",cod:"I4-S11",piso:"S",nom:"Salón I4-S11",ev:"SANDRA PAOLA PEÑA CASTELLANO"},
  {cat:"salon",ed:"BLOI4",cod:"I4-S12",piso:"S",nom:"Salón I4-S12",ev:"SANDRA PAOLA PEÑA CASTELLANO"},
  {cat:"salon",ed:"BLOQB",cod:"32B",piso:"3",nom:"Salón de Clases / Salón 32B",ev:"VIVIANA CARREÑO DURAN"},
  {cat:"salon",ed:"BLOQB",cod:"33B",piso:"3",nom:"Salón de Clases / Salón 33B",ev:"VIVIANA CARREÑO DURAN"},
  {cat:"salon",ed:"BLOQC",cod:"33C",piso:"3",nom:"Salón 33C",ev:"JULIO ALFREDO JIMENEZ MARTINEZ"},
  {cat:"salon",ed:"BLOQC",cod:"14C",piso:"1",nom:"Salón 14C",ev:"JULIO ALFREDO JIMENEZ MARTINEZ"},
  {cat:"salon",ed:"BLOQC",cod:"34C",piso:"3",nom:"Salón 34C",ev:"JULIO ALFREDO JIMENEZ MARTINEZ"},
  {cat:"salon",ed:"BLOQC",cod:"38C",piso:"3",nom:"Salón 38C",ev:"JULIO ALFREDO JIMENEZ MARTINEZ"},
  {cat:"salon",ed:"BLOQC",cod:"24C",piso:"2",nom:"Salón 24C",ev:"JULIO ALFREDO JIMENEZ MARTINEZ"},
  {cat:"salon",ed:"BLOQC",cod:"31C",piso:"3",nom:"Salón 31C",ev:"JULIO ALFREDO JIMENEZ MARTINEZ"},
  {cat:"salon",ed:"BLOQC",cod:"35C",piso:"3",nom:"Salón 35C",ev:"JULIO ALFREDO JIMENEZ MARTINEZ"},
  {cat:"salon",ed:"BLOQC",cod:"13C",piso:"1",nom:"Salón 13C",ev:"JULIO ALFREDO JIMENEZ MARTINEZ"},
  {cat:"salon",ed:"BLOQC",cod:"32C",piso:"3",nom:"Salón 32C",ev:"JULIO ALFREDO JIMENEZ MARTINEZ"},
  {cat:"salon",ed:"BLOQC",cod:"26C",piso:"2",nom:"Salón 26C",ev:"JULIO ALFREDO JIMENEZ MARTINEZ"},
  {cat:"salon",ed:"BLOQC",cod:"22C",piso:"2",nom:"Salón 22C",ev:"JULIO ALFREDO JIMENEZ MARTINEZ"},
  {cat:"salon",ed:"BLOQC",cod:"36C",piso:"3",nom:"Salón 36C",ev:"JULIO ALFREDO JIMENEZ MARTINEZ"},
  {cat:"salon",ed:"BLOQC",cod:"23C",piso:"2",nom:"Salón 23C",ev:"JULIO ALFREDO JIMENEZ MARTINEZ"},
  {cat:"salon",ed:"BLOQC",cod:"A1C",piso:"1",nom:"Salón A1C",ev:"JULIO ALFREDO JIMENEZ MARTINEZ"},
  {cat:"salon",ed:"BLOQC",cod:"A2C",piso:"2",nom:"Salón A2C",ev:"MARIBEL DEL SOCORRO PEREZ ROMERO"},
  {cat:"salon",ed:"BLOQC",cod:"25C",piso:"2",nom:"Salón 25C",ev:"MARIBEL DEL SOCORRO PEREZ ROMERO"},
  {cat:"salon",ed:"BLOQD",cod:"25D",piso:"2",nom:"Salón 25D",ev:"DIANA CAROLINA CASTRO HERNANDEZ"},
  {cat:"salon",ed:"BLOQD",cod:"24D",piso:"2",nom:"Salón 24D",ev:"DIANA CAROLINA CASTRO HERNANDEZ"},
  {cat:"salon",ed:"BLOQD",cod:"23D",piso:"2",nom:"Salón 23D",ev:"DIANA CAROLINA CASTRO HERNANDEZ"},
  {cat:"salon",ed:"BLOQD",cod:"31D",piso:"3",nom:"Salón 31D",ev:"DIANA CAROLINA CASTRO HERNANDEZ"},
  {cat:"salon",ed:"BLOQD",cod:"22D",piso:"2",nom:"Salón 22D",ev:"DIANA CAROLINA CASTRO HERNANDEZ"},
  {cat:"salon",ed:"BLOQE",cod:"32E",piso:"3",nom:"Salón 32E",ev:"ANGELA MERCEDES GONZALEZ VERGARA"},
  {cat:"salon",ed:"BLOQE",cod:"11E",piso:"1",nom:"Salón 11E",ev:"ANGELA MERCEDES GONZALEZ VERGARA"},
  {cat:"salon",ed:"BLOQE",cod:"33E",piso:"3",nom:"Salón 33E",ev:"ANGELA MERCEDES GONZALEZ VERGARA"},
  {cat:"salon",ed:"BLOQE",cod:"22E",piso:"2",nom:"Salón 22E",ev:"ANGELA MERCEDES GONZALEZ VERGARA"},
  {cat:"salon",ed:"BLOQE",cod:"23E",piso:"2",nom:"Salón 23E",ev:"ANGELA MERCEDES GONZALEZ VERGARA"},
  {cat:"salon",ed:"BLOQE",cod:"12E",piso:"1",nom:"Salón 12E",ev:"ANGELA MERCEDES GONZALEZ VERGARA"},
  {cat:"salon",ed:"BLOQE",cod:"24E",piso:"2",nom:"Salón 24E",ev:"ANGELA MERCEDES GONZALEZ VERGARA"},
  {cat:"salon",ed:"BLOQE",cod:"25E",piso:"2",nom:"Salón 25E",ev:"ANGELA MERCEDES GONZALEZ VERGARA"},
  {cat:"salon",ed:"BLOQF",cod:"21F",piso:"2",nom:"Salón 21F",ev:"NITZIA GISELA CARABALLO CABRERA"},
  {cat:"salon",ed:"BLOQF",cod:"22F",piso:"2",nom:"Salón 22F",ev:"NITZIA GISELA CARABALLO CABRERA"},
  {cat:"salon",ed:"BLOQF",cod:"25F",piso:"2",nom:"Salón 25F",ev:"NITZIA GISELA CARABALLO CABRERA"},
  {cat:"salon",ed:"BLOQF",cod:"24F",piso:"2",nom:"Salón 24F",ev:"NITZIA GISELA CARABALLO CABRERA"},
  {cat:"salon",ed:"BLOQF",cod:"23F",piso:"2",nom:"Salón 23F",ev:"NITZIA GISELA CARABALLO CABRERA"},
  {cat:"salon",ed:"BLOQG",cod:"51G",piso:"5",nom:"Sala de Doctorado 1",ev:"IVAN JOSE DE JESUS LUZARDO LUNA"},
  {cat:"salon",ed:"BLOQG",cod:"52G",piso:"5",nom:"Sala de Doctorado 2",ev:"IVAN JOSE DE JESUS LUZARDO LUNA"},
  {cat:"salon",ed:"BLOQG",cod:"53G",piso:"5",nom:"Sala de Doctorado 3",ev:"IVAN JOSE DE JESUS LUZARDO LUNA"},
  {cat:"salon",ed:"BLOQG1",cod:"22G1",piso:"2",nom:"Salón 22G1",ev:"LEILA ANGELA MLAYES HADDAD"},
  {cat:"salon",ed:"BLOQG1",cod:"25G1",piso:"2",nom:"Salón 25G1",ev:"MELISSA DEL CARMEN DELUQUE BASTIDAS"},
  {cat:"salon",ed:"BLOQG1",cod:"21G1",piso:"2",nom:"Salón 21G1",ev:"MELISSA DEL CARMEN DELUQUE BASTIDAS"},
  {cat:"salon",ed:"BLOQG1",cod:"24G1",piso:"2",nom:"Salón 24G1",ev:"MELISSA DEL CARMEN DELUQUE BASTIDAS"},
  {cat:"salon",ed:"BLOQG1",cod:"23G1",piso:"2",nom:"Salón 23G1",ev:"MELISSA DEL CARMEN DELUQUE BASTIDAS"},
  {cat:"salon",ed:"BLOQG1",cod:"31G1",piso:"3",nom:"Salón 31G1",ev:"MELISSA DEL CARMEN DELUQUE BASTIDAS"},
  {cat:"salon",ed:"BLOQG1",cod:"34G1",piso:"3",nom:"Salón 34G1",ev:"MELISSA DEL CARMEN DELUQUE BASTIDAS"},
  {cat:"salon",ed:"BLOQG1",cod:"33G1",piso:"3",nom:"Salón 33G1",ev:"MELISSA DEL CARMEN DELUQUE BASTIDAS"},
  {cat:"salon",ed:"BLOQG1",cod:"32G1",piso:"3",nom:"Salón 32G1",ev:"MELISSA DEL CARMEN DELUQUE BASTIDAS"},
  {cat:"salon",ed:"BLOQG1",cod:"35G1",piso:"3",nom:"Salón 35G1",ev:"MELISSA DEL CARMEN DELUQUE BASTIDAS"},
  {cat:"salon",ed:"BLOQG1",cod:"42G1",piso:"4",nom:"Salón 42G1",ev:"MELISSA DEL CARMEN DELUQUE BASTIDAS"},
  {cat:"salon",ed:"BLOQG1",cod:"45G1",piso:"4",nom:"Salón 45G1",ev:"MELISSA DEL CARMEN DELUQUE BASTIDAS"},
  {cat:"salon",ed:"BLOQG1",cod:"43G1",piso:"4",nom:"Salón 43G1",ev:"MELISSA DEL CARMEN DELUQUE BASTIDAS"},
  {cat:"salon",ed:"BLOQG1",cod:"41G1",piso:"4",nom:"Salón 41G1",ev:"MELISSA DEL CARMEN DELUQUE BASTIDAS"},
  {cat:"salon",ed:"BLOQG1",cod:"44G1",piso:"4",nom:"Salón 44G1",ev:"MELISSA DEL CARMEN DELUQUE BASTIDAS"},
  {cat:"salon",ed:"BLOQG1",cod:"54G1",piso:"5",nom:"Salón 54G1",ev:"MILENA MERCEDES VARELA CARDONA"},
  {cat:"salon",ed:"BLOQG1",cod:"55G1",piso:"5",nom:"Salón 55G1",ev:"MILENA MERCEDES VARELA CARDONA"},
  {cat:"salon",ed:"BLOQG1",cod:"51G1",piso:"5",nom:"Salón 51G1",ev:"MILENA MERCEDES VARELA CARDONA"},
  {cat:"salon",ed:"BLOQG1",cod:"52G1",piso:"5",nom:"Salón 52G1",ev:"MILENA MERCEDES VARELA CARDONA"},
  {cat:"salon",ed:"BLOQG1",cod:"53G1",piso:"5",nom:"Salón 53G1",ev:"MILENA MERCEDES VARELA CARDONA"},
  {cat:"salon",ed:"BLOQG2",cod:"12G2",piso:"1",nom:"Salón 12G2",ev:"Hailyn Kelly Mejia Piedris"},
  {cat:"salon",ed:"BLOQG2",cod:"11G2",piso:"1",nom:"Salón 11G2",ev:"IVAN JOSE DE JESUS LUZARDO LUNA"},
  {cat:"salon",ed:"BLOQG2",cod:"25G2",piso:"2",nom:"Salón Harvard 2 -salón magistral",ev:"IVAN JOSE DE JESUS LUZARDO LUNA"},
  {cat:"salon",ed:"BLOQG2",cod:"23G2",piso:"2",nom:"Salón Harvard- salón magistral",ev:"IVAN JOSE DE JESUS LUZARDO LUNA"},
  {cat:"salon",ed:"BLOQG2",cod:"54G2",piso:"5",nom:"Sala de Doctorado 4",ev:"IVAN JOSE DE JESUS LUZARDO LUNA"},
  {cat:"salon",ed:"BLOQG2",cod:"31G2",piso:"3",nom:"Salón 31G2",ev:"JOHANNA HELENA MORENO MONTAÑEZ"},
  {cat:"salon",ed:"BLOQG2",cod:"32G2",piso:"3",nom:"Salón 32G2",ev:"JOHANNA HELENA MORENO MONTAÑEZ"},
  {cat:"salon",ed:"BLOQG2",cod:"36G2",piso:"3",nom:"Salón 36G2",ev:"JOHANNA HELENA MORENO MONTAÑEZ"},
  {cat:"salon",ed:"BLOQG2",cod:"33G2",piso:"3",nom:"Salón 33G2",ev:"JOHANNA HELENA MORENO MONTAÑEZ"},
  {cat:"salon",ed:"BLOQG2",cod:"37G2",piso:"3",nom:"Salón 37G2",ev:"JOHANNA HELENA MORENO MONTAÑEZ"},
  {cat:"salon",ed:"BLOQG2",cod:"38G2",piso:"3",nom:"Salón 38G2",ev:"JOHANNA HELENA MORENO MONTAÑEZ"},
  {cat:"salon",ed:"BLOQG2",cod:"35G2",piso:"3",nom:"Salón 35G2",ev:"JOHANNA HELENA MORENO MONTAÑEZ"},
  {cat:"salon",ed:"BLOQG2",cod:"34G2",piso:"3",nom:"Salón 34G2",ev:"JOHANNA HELENA MORENO MONTAÑEZ"},
  {cat:"salon",ed:"BLOQG2",cod:"21G2",piso:"2",nom:"Salón 21G2",ev:"LEILA ANGELA MLAYES HADDAD"},
  {cat:"salon",ed:"BLOQG2",cod:"22G2",piso:"2",nom:"Oralidad- salón magistral",ev:"LEILA ANGELA MLAYES HADDAD"},
  {cat:"salon",ed:"BLOQG2",cod:"13G2",piso:"1",nom:"Salón 13G2",ev:"MILENA MERCEDES VARELA CARDONA"},
  {cat:"salon",ed:"BLOQG2",cod:"51G2",piso:"5",nom:"Salón 51G2",ev:"MILENA MERCEDES VARELA CARDONA"},
  {cat:"salon",ed:"BLOQJ1",cod:"14J",piso:"1",nom:"Salon de clases 14J",ev:"ELMA CRISTINA MORALES CORTINA"},
  {cat:"salon",ed:"BLOQJ1",cod:"17J",piso:"1",nom:"Salon de clases 17J",ev:"ELMA CRISTINA MORALES CORTINA"},
  {cat:"salon",ed:"BLOQJ1",cod:"16J",piso:"1",nom:"Salon de clases 16J",ev:"ELMA CRISTINA MORALES CORTINA"},
  {cat:"salon",ed:"BLOQJ1",cod:"15J",piso:"1",nom:"Salon de clases 15J",ev:"ELMA CRISTINA MORALES CORTINA"},
  {cat:"salon",ed:"BLOQJ1",cod:"18J",piso:"1",nom:"Salon de clases 18J",ev:"ELMA CRISTINA MORALES CORTINA"},
  {cat:"salon",ed:"BLOQJ1",cod:"33J",piso:"3",nom:"Salon de clases 33J",ev:"MARGARITA ROSA DE ALBA AVENDAÑO"},
  {cat:"salon",ed:"BLOQJ1",cod:"38J",piso:"3",nom:"Salon de clases 38J",ev:"MARGARITA ROSA DE ALBA AVENDAÑO"},
  {cat:"salon",ed:"BLOQJ1",cod:"36J",piso:"3",nom:"Salon de clases 36J",ev:"MARGARITA ROSA DE ALBA AVENDAÑO"},
  {cat:"salon",ed:"BLOQJ1",cod:"35J",piso:"3",nom:"Salon de clases 35J",ev:"MARGARITA ROSA DE ALBA AVENDAÑO"},
  {cat:"salon",ed:"BLOQJ1",cod:"34J",piso:"3",nom:"Salon de clases 34J",ev:"MARGARITA ROSA DE ALBA AVENDAÑO"},
  {cat:"salon",ed:"BLOQJ1",cod:"31J",piso:"3",nom:"Salon de clases 31J",ev:"MARGARITA ROSA DE ALBA AVENDAÑO"},
  {cat:"salon",ed:"BLOQJ1",cod:"37J",piso:"3",nom:"Salon de clases 37J",ev:"MARGARITA ROSA DE ALBA AVENDAÑO"},
  {cat:"salon",ed:"BLOQJ1",cod:"32J",piso:"3",nom:"Salon de clases 32J",ev:"MARGARITA ROSA DE ALBA AVENDAÑO"},
  {cat:"salon",ed:"BLOQJ1",cod:"11J",piso:"1",nom:"Salon de clases 11J",ev:"MARIA ALEJANDRA SOCARRAS MEDRANO"},
  {cat:"salon",ed:"BLOQJ1",cod:"13J",piso:"1",nom:"Salon de clases 13J",ev:"MARIA ALEJANDRA SOCARRAS MEDRANO"},
  {cat:"salon",ed:"BLOQJ1",cod:"12J",piso:"1",nom:"Salon de clases 12J",ev:"MARIA ALEJANDRA SOCARRAS MEDRANO"},
  {cat:"salon",ed:"BLOQJ1",cod:"25J",piso:"2",nom:"Salon de clases 25J",ev:"MARIA ALEJANDRA SOCARRAS MEDRANO"},
  {cat:"salon",ed:"BLOQJ1",cod:"22J",piso:"2",nom:"Salon de clases 22J",ev:"MARIA ALEJANDRA SOCARRAS MEDRANO"},
  {cat:"salon",ed:"BLOQJ1",cod:"24J",piso:"2",nom:"Salon de clases 24J",ev:"MARIA ALEJANDRA SOCARRAS MEDRANO"},
  {cat:"salon",ed:"BLOQJ1",cod:"21J",piso:"2",nom:"Salon de clases 21J",ev:"MARIA ALEJANDRA SOCARRAS MEDRANO"},
  {cat:"salon",ed:"BLOQJ1",cod:"26J",piso:"2",nom:"Salon de clases 26J",ev:"MARIA ALEJANDRA SOCARRAS MEDRANO"},
  {cat:"salon",ed:"BLOQJ1",cod:"23J",piso:"2",nom:"Salon de clases 23J",ev:"MARIA ALEJANDRA SOCARRAS MEDRANO"},
  {cat:"salon",ed:"BLOQJ1",cod:"28J",piso:"2",nom:"Salon de clases 28J",ev:"MARIA ALEJANDRA SOCARRAS MEDRANO"},
  {cat:"salon",ed:"BLOQJ1",cod:"27J",piso:"2",nom:"Salon de clases27J",ev:"MARIA ALEJANDRA SOCARRAS MEDRANO"},
  {cat:"salon",ed:"BLOQK",cod:"21K",piso:"2",nom:"SALON 21K",ev:"Hailyn Kelly Mejia Piedris"},
  {cat:"salon",ed:"BLOQK",cod:"31K",piso:"3",nom:"SALON 31K",ev:"Hailyn Kelly Mejia Piedris"},
  {cat:"salon",ed:"BLOQK",cod:"92K",piso:"9",nom:"Salón 92K",ev:"PATRICIA JAIMES TABOADA"},
  {cat:"salon",ed:"BLOQK",cod:"93K",piso:"9",nom:"Salón 93K",ev:"PATRICIA JAIMES TABOADA"},
  {cat:"salon",ed:"BLOQK",cod:"45K",piso:"4",nom:"Salón 45K",ev:"PATRICIA JAIMES TABOADA"},
  {cat:"salon",ed:"BLOQK",cod:"41K",piso:"4",nom:"Salón 41K",ev:"PATRICIA JAIMES TABOADA"},
  {cat:"salon",ed:"BLOQK",cod:"43K",piso:"4",nom:"Salón 43K",ev:"PATRICIA JAIMES TABOADA"},
  {cat:"salon",ed:"BLOQK",cod:"46K",piso:"4",nom:"Salón 46K",ev:"PATRICIA JAIMES TABOADA"},
  {cat:"salon",ed:"BLOQK",cod:"91K",piso:"9",nom:"Salón 91K",ev:"PATRICIA JAIMES TABOADA"},
  {cat:"salon",ed:"BLOQK",cod:"44K",piso:"4",nom:"Salón 44K",ev:"PATRICIA JAIMES TABOADA"},
  {cat:"salon",ed:"BLOQK",cod:"42K",piso:"4",nom:"Salón 42K",ev:"PATRICIA JAIMES TABOADA"},
  {cat:"salon",ed:"BLOQK",cod:"94K",piso:"9",nom:"Salón 94K",ev:"PATRICIA JAIMES TABOADA"},
  {cat:"salon",ed:"BLOQK",cod:"95K",piso:"9",nom:"Salón 95K",ev:"PATRICIA JAIMES TABOADA"},
  {cat:"salon",ed:"BLOQK",cod:"97K",piso:"9",nom:"Salón 97K",ev:"PATRICIA JAIMES TABOADA"},
  {cat:"salon",ed:"BLOQK",cod:"96K",piso:"9",nom:"Salón 96K",ev:"PATRICIA JAIMES TABOADA"},
  {cat:"salon",ed:"BLOQM",cod:"5M",piso:"1",nom:"Salón de clase música 5M",ev:"Alexander Villegas Mendoza"},
  {cat:"salon",ed:"BLOQM",cod:"4M",piso:"1",nom:"4M",ev:"Alexander Villegas Mendoza"},
  {cat:"salon",ed:"BLOQM",cod:"1M",piso:"1",nom:"1M",ev:"Alexander Villegas Mendoza"},
  {cat:"salon",ed:"BLOQM",cod:"2M",piso:"1",nom:"2M",ev:"Alexander Villegas Mendoza"},
  {cat:"salon",ed:"BLOQM",cod:"3M",piso:"1",nom:"3M",ev:"Alexander Villegas Mendoza"},
  {cat:"salon",ed:"COLIS",cod:"SAL1",piso:"1",nom:"Salón De Música No.1.",ev:"EDWIN LUIS ANGULO LUGO"},
  {cat:"sala_pc",ed:"BACA",cod:"BLB3",piso:"",nom:"Biblab 3",ev:"JOAQUIN JESUS PINTO ROMERO"},
  {cat:"sala_pc",ed:"BKCP",cod:"BLB2",piso:"1",nom:"Biblab 2",ev:"GRACE MARIA SANCHEZ PATERNOSTRO"},
  {cat:"sala_pc",ed:"BKCP",cod:"BLB1",piso:"1",nom:"Biblab 1",ev:"GRACE MARIA SANCHEZ PATERNOSTRO"},
  {cat:"sala_pc",ed:"BLOQB",cod:"SDU3",piso:"2",nom:"Sala de Usuario / Sala de Usuarios No. 3",ev:"VIVIANA CARREÑO DURAN"},
  {cat:"sala_pc",ed:"BLOQB",cod:"SDU5",piso:"3",nom:"Sala de Usuario/ Sala de Usuarios No. 5",ev:"VIVIANA CARREÑO DURAN"},
  {cat:"sala_pc",ed:"BLOQB",cod:"SIN1",piso:"",nom:"sala de usuario / Sala de Internet 1",ev:"VIVIANA CARREÑO DURAN"},
  {cat:"sala_pc",ed:"BLOQB",cod:"SDU2",piso:"2",nom:"Sala de usuario /Sala de Usuarios No. 2",ev:"VIVIANA CARREÑO DURAN"},
  {cat:"sala_pc",ed:"BLOQC",cod:"SDU1",piso:"1",nom:"Sala de Usuario / Sala de Usuarios 1",ev:"MARIBEL DEL SOCORRO PEREZ ROMERO"},
  {cat:"sala_pc",ed:"BLOQD",cod:"SIN2",piso:"",nom:"Sala de Internet 2",ev:"DIANA CAROLINA CASTRO HERNANDEZ"},
  {cat:"sala_pc",ed:"BLOQD",cod:"SDU4",piso:"3",nom:"Sala de Usuarios No. 4",ev:"DIANA CAROLINA CASTRO HERNANDEZ"},
  {cat:"sala_pc",ed:"BLOQG",cod:"5-0G",piso:"5",nom:"Aula Digital",ev:"LEILA ANGELA MLAYES HADDAD"},
  {cat:"sala_pc",ed:"BLOQG",cod:"SDU6",piso:"5",nom:"Sala de Usuarios No. 6",ev:"LEILA ANGELA MLAYES HADDAD"},
  {cat:"sala_pc",ed:"BLOQG2",cod:"SDU7",piso:"5",nom:"Sala de Usuarios No. 7",ev:"LEILA ANGELA MLAYES HADDAD"},
  {cat:"sala_pc",ed:"BLOQJ1",cod:"SDU-51J",piso:"5",nom:"Sala de usuarios No. 11",ev:"VALERIA MELISSA FONTALVO QUINTERO"},
  {cat:"sala_pc",ed:"BLOQK",cod:"SDU8",piso:"",nom:"Sala de Usuarios No. 8",ev:"OSVALDO DE JESUS GAMARRA AMARIS"},
  {cat:"sala_pc",ed:"BLOQK",cod:"SDU10",piso:"",nom:"Sala de Usuarios No. 10",ev:"OSVALDO DE JESUS GAMARRA AMARIS"},
  {cat:"sala_pc",ed:"BLOQK",cod:"SDU9",piso:"",nom:"Sala de Usuarios No. 9",ev:"OSVALDO DE JESUS GAMARRA AMARIS"},
  {cat:"parqueadero",ed:"FUERA",cod:"P8",piso:"",nom:"Parqueadero Exterior N° 8",ev:"JUAN CAMILO PERALTA"},
  {cat:"parqueadero",ed:"FUERA",cod:"P9",piso:"",nom:"Parqueadero Exterior N° 9",ev:"JUAN CAMILO PERALTA"},
  {cat:"parqueadero",ed:"FUERA",cod:"P12",piso:"",nom:"Parqueadero Exterior N° 12",ev:"JUAN CAMILO PERALTA"},
  {cat:"laboratorio",ed:"1L6",cod:"3L-10",piso:"1",nom:"Salón 3L-10",ev:"ELMA CRISTINA MORALES CORTINA"},
  {cat:"laboratorio",ed:"1L6",cod:"3L-11",piso:"1",nom:"Salón 3L-11",ev:"ELMA CRISTINA MORALES CORTINA"},
  {cat:"laboratorio",ed:"1L6",cod:"1L6-11",piso:"1",nom:"Lab. de Desarrollo de modelos y prototipos",ev:"GUSTAVO ADOLFO LOPEZ HENRIQUEZ"},
  {cat:"laboratorio",ed:"1L6",cod:"1L6-21",piso:"2",nom:"Sala de Diseño Estudiantes",ev:"GUSTAVO ADOLFO LOPEZ HENRIQUEZ"},
  {cat:"laboratorio",ed:"1L6",cod:"1L6-22",piso:"2",nom:"Sala Diseño de Estudiantes",ev:"GUSTAVO ADOLFO LOPEZ HENRIQUEZ"},
  {cat:"laboratorio",ed:"1L6",cod:"1L6-31",piso:"3",nom:"Lab. de Sistemas Digitales",ev:"GUSTAVO ADOLFO LOPEZ HENRIQUEZ"},
  {cat:"laboratorio",ed:"1L6",cod:"1L6-32",piso:"3",nom:"Sala 2 Investigación y Desarrollo",ev:"GUSTAVO ADOLFO LOPEZ HENRIQUEZ"},
  {cat:"laboratorio",ed:"1L6",cod:"1L6-33",piso:"3",nom:"Sala 3 Investigación y Desarrollo",ev:"GUSTAVO ADOLFO LOPEZ HENRIQUEZ"},
  {cat:"laboratorio",ed:"1L6",cod:"1L6-34",piso:"3",nom:"Sala 4 Investigación y Desarrollo",ev:"GUSTAVO ADOLFO LOPEZ HENRIQUEZ"},
  {cat:"laboratorio",ed:"1L6",cod:"1L6-35",piso:"3",nom:"Sala 5 Investigación - Lab.Telemática",ev:"GUSTAVO ADOLFO LOPEZ HENRIQUEZ"},
  {cat:"laboratorio",ed:"1L6",cod:"1L6-36",piso:"3",nom:"Sala 6 Investigación y Desarrollo",ev:"GUSTAVO ADOLFO LOPEZ HENRIQUEZ"},
  {cat:"laboratorio",ed:"1L6",cod:"1L6-37",piso:"3",nom:"Sala 7 Investigación y Desarrollo",ev:"GUSTAVO ADOLFO LOPEZ HENRIQUEZ"},
  {cat:"laboratorio",ed:"1L6",cod:"1L6-38",piso:"3",nom:"Sala 8 Investigación y Desarrollo",ev:"GUSTAVO ADOLFO LOPEZ HENRIQUEZ"},
  {cat:"laboratorio",ed:"1L6",cod:"1L6-39",piso:"3",nom:"Sala 9 Investigación y Desarrollo",ev:"GUSTAVO ADOLFO LOPEZ HENRIQUEZ"},
  {cat:"laboratorio",ed:"1L6",cod:"3L-12",piso:"1",nom:"Laboratorio Investigacion departamento de fisica",ev:"GUSTAVO ADOLFO LOPEZ HENRIQUEZ"},
  {cat:"laboratorio",ed:"1L6",cod:"4L-1",piso:"4",nom:"Salón 4L-1 Diseño digital",ev:"MILENA MERCEDES VARELA CARDONA"},
  {cat:"laboratorio",ed:"1L6",cod:"4L-2",piso:"4",nom:"Salón 4L-2 Diseño digital",ev:"MILENA MERCEDES VARELA CARDONA"},
  {cat:"laboratorio",ed:"1L6",cod:"4L-3",piso:"4",nom:"Salón 4L-3 Diseño digital",ev:"MILENA MERCEDES VARELA CARDONA"},
  {cat:"laboratorio",ed:"BKCP",cod:"L5-1",piso:"S",nom:"Lab. de Fotografía",ev:"SANDRA PAOLA PEÑA CASTELLANO"},
  {cat:"laboratorio",ed:"BKCP",cod:"L5-2",piso:"S",nom:"Estudio de Televisión",ev:"SANDRA PAOLA PEÑA CASTELLANO"},
  {cat:"laboratorio",ed:"BLOI1",cod:"LI1-1",piso:"1",nom:"Lab. de Idiomas 1",ev:"Hailyn Kelly Mejia Piedris"},
  {cat:"laboratorio",ed:"BLOI1",cod:"LI1-2",piso:"1",nom:"Lab. de Idiomas 2",ev:"Hailyn Kelly Mejia Piedris"},
  {cat:"laboratorio",ed:"BLOI4",cod:"LI4-4",piso:"1",nom:"Lab. LI4-4",ev:"EYLEEN GIOBET CASTILLO MENDOZA"},
  {cat:"laboratorio",ed:"BLOQB",cod:"34B",piso:"3",nom:"Salón de Dibujo",ev:"VIVIANA CARREÑO DURAN"},
  {cat:"laboratorio",ed:"BLOQC",cod:"21C",piso:"2",nom:"Taller Arquitectura",ev:"MARIBEL DEL SOCORRO PEREZ ROMERO"},
  {cat:"laboratorio",ed:"BLOQC",cod:"37C",piso:"3",nom:"Taller de Diseño y Arquitectura",ev:"MARIBEL DEL SOCORRO PEREZ ROMERO"},
  {cat:"laboratorio",ed:"BLOQC",cod:"LC-1",piso:"S",nom:"Lab. Ing. de Control",ev:"MARIBEL DEL SOCORRO PEREZ ROMERO"},
  {cat:"laboratorio",ed:"BLOQC",cod:"LC-2",piso:"S",nom:"Lab. de Ing Electrónica y comunicaciones",ev:"MARIBEL DEL SOCORRO PEREZ ROMERO"},
  {cat:"laboratorio",ed:"BLOQC",cod:"LC-3",piso:"S",nom:"Lab. diseño de sofware y redes",ev:"MARIBEL DEL SOCORRO PEREZ ROMERO"},
  {cat:"laboratorio",ed:"BLOQC",cod:"LC-4",piso:"S",nom:"Laboratorio / Sala de usuario-Lab. Circuitos y Maq. Eléctricas",ev:"MARIBEL DEL SOCORRO PEREZ ROMERO"},
  {cat:"laboratorio",ed:"BLOQC",cod:"LC-5",piso:"S",nom:"Laboratorio / Sala de Usuario -Lab. de Transmisión",ev:"MARIBEL DEL SOCORRO PEREZ ROMERO"},
  {cat:"laboratorio",ed:"BLOQC",cod:"LC-6",piso:"S",nom:"Lab. de Infraestructura Tecnologica Informatica",ev:"MARIBEL DEL SOCORRO PEREZ ROMERO"},
  {cat:"laboratorio",ed:"BLOQD",cod:"21D",piso:"2",nom:"Salón 21D",ev:"DIANA CAROLINA CASTRO HERNANDEZ"},
  {cat:"laboratorio",ed:"BLOQD",cod:"LD1",piso:"S",nom:"Laboratorio de economia experimental",ev:"DIANA CAROLINA CASTRO HERNANDEZ"},
  {cat:"laboratorio",ed:"BLOQE",cod:"LE-1",piso:"",nom:"Lab. Enfermedades Tropicales",ev:"ANGELA MERCEDES GONZALEZ VERGARA"},
  {cat:"laboratorio",ed:"BLOQE",cod:"LE-3_2",piso:"",nom:"Laboratorio de Morfología",ev:"ANGELA MERCEDES GONZALEZ VERGARA"},
  {cat:"laboratorio",ed:"BLOQE",cod:"LE-4",piso:"",nom:"Lab. de Enfermería",ev:"ANGELA MERCEDES GONZALEZ VERGARA"},
  {cat:"laboratorio",ed:"BLOQE",cod:"LE-5",piso:"",nom:"Lab. de Psicología",ev:"ANGELA MERCEDES GONZALEZ VERGARA"},
  {cat:"laboratorio",ed:"BLOQF",cod:"LF-1",piso:"",nom:"Lab. Fisiología e Histología y Microbiologia",ev:"NITZIA GISELA CARABALLO CABRERA"},
  {cat:"laboratorio",ed:"BLOQG2",cod:"LG2-51",piso:"5",nom:"Lab. Relaciones Internacionales",ev:"LEILA ANGELA MLAYES HADDAD"},
  {cat:"laboratorio",ed:"BLOQG2",cod:"LG2-52",piso:"5",nom:"Lab. Comunicación Social",ev:"LEILA ANGELA MLAYES HADDAD"},
  {cat:"laboratorio",ed:"BLOQJ",cod:"LJ-5",piso:"",nom:"Pendiente",ev:"VALERIA MELISSA FONTALVO QUINTERO"},
  {cat:"laboratorio",ed:"BLOQJ1",cod:"L-41J",piso:"4",nom:"Laboratorio Instituto de Idiomas No 5",ev:"MARGARITA ROSA DE ALBA AVENDAÑO"},
  {cat:"laboratorio",ed:"BLOQJ1",cod:"L-42J",piso:"4",nom:"Laboratorio Instituto de Idiomas No 6",ev:"MARGARITA ROSA DE ALBA AVENDAÑO"},
  {cat:"laboratorio",ed:"BLOQJ1",cod:"L-43J",piso:"4",nom:"Laboratorio Experimental de Matematicas",ev:"MARGARITA ROSA DE ALBA AVENDAÑO"},
  {cat:"laboratorio",ed:"BLOQJ1",cod:"L-S1J",piso:"S",nom:"Laboratorio de Petrografia óptica",ev:"MARGARITA ROSA DE ALBA AVENDAÑO"},
  {cat:"laboratorio",ed:"BLOQJ1",cod:"L-S2J",piso:"S",nom:"Laboratorio de Cartografia y Geomorfologia",ev:"MARGARITA ROSA DE ALBA AVENDAÑO"},
  {cat:"laboratorio",ed:"BLOQJ1",cod:"L-S5J",piso:"S",nom:"Laboratorio de Geología Física",ev:"MARGARITA ROSA DE ALBA AVENDAÑO"},
  {cat:"laboratorio",ed:"BLOQJ1",cod:"L-51J",piso:"5",nom:"Laboratorio Aula Taller de Comunicación Social y Periodismo",ev:"VALERIA MELISSA FONTALVO QUINTERO"},
  {cat:"laboratorio",ed:"BLOQJ1",cod:"L-52J",piso:"5",nom:"Laboratorio de Educación",ev:"VALERIA MELISSA FONTALVO QUINTERO"},
  {cat:"laboratorio",ed:"BLOQJ1",cod:"L-53J",piso:"5",nom:"Laboratorio de Arqueologia",ev:"VALERIA MELISSA FONTALVO QUINTERO"},
  {cat:"laboratorio",ed:"BLOQK",cod:"6-4L",piso:"6",nom:"Lab Termo Fluidos",ev:"CESAR MANUEL STAND ZAMBRANO"},
  {cat:"laboratorio",ed:"BLOQK",cod:"6-5L",piso:"6",nom:"Lab. Biocombustible",ev:"CESAR MANUEL STAND ZAMBRANO"},
  {cat:"laboratorio",ed:"BLOQK",cod:"6-6L",piso:"6",nom:"Lab. de Biotecnología",ev:"CESAR MANUEL STAND ZAMBRANO"},
  {cat:"laboratorio",ed:"BLOQK",cod:"6-8L",piso:"6",nom:"Laboratorio de Mecatronica",ev:"CESAR MANUEL STAND ZAMBRANO"},
  {cat:"laboratorio",ed:"BLOQK",cod:"6-9L",piso:"6",nom:"Lab. Mecánica de Máquinas y Diseños",ev:"CESAR MANUEL STAND ZAMBRANO"},
  {cat:"laboratorio",ed:"BLOQK",cod:"S1-10L",piso:"S",nom:"Lab. de Soldadura",ev:"CESAR MANUEL STAND ZAMBRANO"},
  {cat:"laboratorio",ed:"BLOQK",cod:"S1-11L",piso:"S",nom:"Lab. Geotecnia y Materiales Constr.",ev:"CESAR MANUEL STAND ZAMBRANO"},
  {cat:"laboratorio",ed:"BLOQK",cod:"S1-4L",piso:"S",nom:"Lab. Metalografía",ev:"CESAR MANUEL STAND ZAMBRANO"},
  {cat:"laboratorio",ed:"BLOQK",cod:"S1-5L",piso:"S",nom:"Lab. de Ensayos de Materiales",ev:"CESAR MANUEL STAND ZAMBRANO"},
  {cat:"laboratorio",ed:"BLOQK",cod:"S1-6L",piso:"S",nom:"Lab. de Prototipos",ev:"CESAR MANUEL STAND ZAMBRANO"},
  {cat:"laboratorio",ed:"BLOQK",cod:"S1-7L",piso:"S",nom:"Lab. Centro de Mediciones y Coordenadas",ev:"CESAR MANUEL STAND ZAMBRANO"},
  {cat:"laboratorio",ed:"BLOQK",cod:"S1-8L",piso:"S",nom:"Lab. de Manufactura",ev:"CESAR MANUEL STAND ZAMBRANO"},
  {cat:"laboratorio",ed:"BLOQK",cod:"S1-9L",piso:"S",nom:"Lab. de Materiales De Ingeniería",ev:"CESAR MANUEL STAND ZAMBRANO"},
  {cat:"laboratorio",ed:"BLOQK",cod:"1-1L",piso:"1",nom:"Lab. de Aprendizaje Estudiantes",ev:"HAROLD JOSE RIOS BRUGES"},
  {cat:"laboratorio",ed:"BLOQK",cod:"1-2L",piso:"1",nom:"Lab. de Aprendizaje Docente",ev:"HAROLD JOSE RIOS BRUGES"},
  {cat:"laboratorio",ed:"BLOQK",cod:"4-1L",piso:"4",nom:"Diseño Digital",ev:"HAROLD JOSE RIOS BRUGES"},
  {cat:"laboratorio",ed:"BLOQK",cod:"4-2L",piso:"4",nom:"Estudio de Fotografia",ev:"HAROLD JOSE RIOS BRUGES"},
  {cat:"laboratorio",ed:"BLOQK",cod:"L4-1",piso:"4",nom:"Lab. Robótica Industrial",ev:"HAROLD JOSE RIOS BRUGES"},
  {cat:"laboratorio",ed:"BLOQK",cod:"5-2L",piso:"5",nom:"Sala de Computo Ing civil",ev:"HAROLD JOSE RIOS BRUGES"},
  {cat:"laboratorio",ed:"BLOQK",cod:"6-2L",piso:"6",nom:"Lab Mediciones y Control",ev:"HAROLD JOSE RIOS BRUGES"},
  {cat:"laboratorio",ed:"BLOQK",cod:"6-3L",piso:"6",nom:"Lab Ciencias de la Computacion",ev:"HAROLD JOSE RIOS BRUGES"},
  {cat:"laboratorio",ed:"BLOQK",cod:"7-1L",piso:"7",nom:"Lab. Computacional Ing. Industrial",ev:"HAROLD JOSE RIOS BRUGES"},
  {cat:"laboratorio",ed:"BLOQK",cod:"7-2L",piso:"7",nom:"Lab. Investigación de Operaciones",ev:"HAROLD JOSE RIOS BRUGES"},
  {cat:"laboratorio",ed:"BLOQK",cod:"7-3L",piso:"7",nom:"Lab Higiene y seguridad Industrial",ev:"HAROLD JOSE RIOS BRUGES"},
  {cat:"laboratorio",ed:"BLOQK",cod:"7-4L",piso:"7",nom:"Lab. Operaciones y Logística",ev:"HAROLD JOSE RIOS BRUGES"},
  {cat:"laboratorio",ed:"BLOQK",cod:"ECO",piso:"",nom:"Centro de escritura",ev:"HAROLD JOSE RIOS BRUGES"},
  {cat:"laboratorio",ed:"BLOQK",cod:"3-1L",piso:"3",nom:"Lab Mecanica Computacional y Diseño",ev:"JUAN CARLOS GALEANO MUÑOZ"},
  {cat:"laboratorio",ed:"BLOQK",cod:"3-2L",piso:"3",nom:"Lab. de Hidráulica e Ing. Ambiental",ev:"JUAN CARLOS GALEANO MUÑOZ"},
  {cat:"laboratorio",ed:"BLOQK",cod:"S1-1L",piso:"S",nom:"Lab. de Tratamientos Térmicos",ev:"JUAN CARLOS GALEANO MUÑOZ"},
  {cat:"laboratorio",ed:"BLOQK",cod:"S1-2L",piso:"S",nom:"Lab. Corrosión",ev:"JUAN CARLOS GALEANO MUÑOZ"},
  {cat:"laboratorio",ed:"BLOQK",cod:"S1-3L",piso:"S",nom:"Lab. de Microscopia Electrónica",ev:"JUAN CARLOS GALEANO MUÑOZ"},
  {cat:"laboratorio",ed:"BLOQM",cod:"L11M",piso:"1",nom:"Lab de producción y composición músical",ev:"IRMINA DEL CARMEN RICAURTE MARTINEZ"},
  {cat:"laboratorio",ed:"CANCH",cod:"CDA-1L",piso:"1",nom:"Arquitectura Tropical",ev:"IRMINA DEL CARMEN RICAURTE MARTINEZ"},
  {cat:"laboratorio",ed:"CANCH",cod:"CDA-2L",piso:"1",nom:"Lab Energia Renovables",ev:"IRMINA DEL CARMEN RICAURTE MARTINEZ"},
  {cat:"laboratorio",ed:"L1",cod:"L1-1",piso:"1",nom:"Lab. de Química",ev:"YULEINE YANIET MORENO FONTALVO"},
  {cat:"laboratorio",ed:"L1",cod:"L1-2",piso:"1",nom:"Lab. de Fitoquímica",ev:"YULEINE YANIET MORENO FONTALVO"},
  {cat:"laboratorio",ed:"L1",cod:"L1-3",piso:"1",nom:"Lab. de Física Calor",ev:"YULEINE YANIET MORENO FONTALVO"},
  {cat:"laboratorio",ed:"L1",cod:"L1-4",piso:"1",nom:"Lab. Física Mecánica",ev:"YULEINE YANIET MORENO FONTALVO"},
  {cat:"laboratorio",ed:"L1",cod:"L1-5",piso:"1",nom:"Lab. de Física Eléctrica",ev:"YULEINE YANIET MORENO FONTALVO"},
  {cat:"laboratorio",ed:"L2",cod:"L2-2",piso:"1",nom:"Lab. Multifuncional Bioquimica",ev:"YULEINE YANIET MORENO FONTALVO"},
  {cat:"laboratorio",ed:"L2",cod:"L2-3",piso:"1",nom:"Lab. Multifuncional Biología",ev:"YULEINE YANIET MORENO FONTALVO"},
  {cat:"laboratorio",ed:"L2",cod:"L2-4",piso:"1",nom:"Lab. de Genética",ev:"YULEINE YANIET MORENO FONTALVO"},
  {cat:"laboratorio",ed:"L2",cod:"L2-5",piso:"1",nom:"Laboratorio de Investigacion Biodiversidad",ev:"YULEINE YANIET MORENO FONTALVO"},
  {cat:"laboratorio",ed:"L2",cod:"L2-6",piso:"1",nom:"Laboratorio de Quimica y Bioiologia",ev:"YULEINE YANIET MORENO FONTALVO"},
  {cat:"laboratorio",ed:"L2",cod:"L2-7",piso:"1",nom:"Laboratorio Computacional de Quimica y Biologia",ev:"YULEINE YANIET MORENO FONTALVO"},
  {cat:"laboratorio",ed:"L3",cod:"L3-1",piso:"1",nom:"Laboratorio de Mercadeo",ev:"YULEINE YANIET MORENO FONTALVO"},
  {cat:"laboratorio",ed:"L3",cod:"L3-2",piso:"1",nom:"Lab. Inm. y Biol. Molecular",ev:"YULEINE YANIET MORENO FONTALVO"},
  {cat:"laboratorio",ed:"L4",cod:"2-1 L4",piso:"2",nom:"Laboratorio simulacion preclinica odontologica",ev:"IRMINA DEL CARMEN RICAURTE MARTINEZ"},
  {cat:"laboratorio",ed:"L4",cod:"2-2 L4",piso:"2",nom:"Laboratorio multifuncional de Materiales dentales",ev:"IRMINA DEL CARMEN RICAURTE MARTINEZ"},
  {cat:"laboratorio",ed:"L4",cod:"2-3 L4",piso:"2",nom:"Laboratorio rayos X odontologicos",ev:"IRMINA DEL CARMEN RICAURTE MARTINEZ"},
  {cat:"laboratorio",ed:"L4",cod:"2-4 L4",piso:"2",nom:"Laboratorio simulacion preclinica odontologica",ev:"IRMINA DEL CARMEN RICAURTE MARTINEZ"},
  {cat:"laboratorio",ed:"L5",cod:"L5-11",piso:"1",nom:"Sala de Computadores de Pedagogia Infantil",ev:"IRMINA DEL CARMEN RICAURTE MARTINEZ"},
  {cat:"laboratorio",ed:"L5",cod:"L5-12",piso:"1",nom:"Lab. virologia",ev:"IRMINA DEL CARMEN RICAURTE MARTINEZ"},
  {cat:"laboratorio",ed:"L5",cod:"LJ-1",piso:"1",nom:"Lab. Lic. En Pedagogía Infantil",ev:"IRMINA DEL CARMEN RICAURTE MARTINEZ"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS03",piso:"",nom:"Jardín de alrededor de comedor funcionarios",ev:"ELMA CRISTINA MORALES CORTINA"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS08",piso:"",nom:"Jardín administrativo 2",ev:"ELMA CRISTINA MORALES CORTINA"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS01",piso:"",nom:"Jardín frente Biblioteca",ev:"HOLLY ANDREA DE LA ROSA RODRIGUEZ"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS02",piso:"",nom:"Jardín posterior Biblioteca",ev:"HOLLY ANDREA DE LA ROSA RODRIGUEZ"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS04",piso:"",nom:"Jardín Laboratorio 1",ev:"HOLLY ANDREA DE LA ROSA RODRIGUEZ"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS05",piso:"",nom:"Jardín Laboratorio 2",ev:"HOLLY ANDREA DE LA ROSA RODRIGUEZ"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS14",piso:"",nom:"Jardín entre Bloque B y Bloque C",ev:"HOLLY ANDREA DE LA ROSA RODRIGUEZ"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS33",piso:"",nom:"Jardín Casa Blanca (Administrativo 1)",ev:"HOLLY ANDREA DE LA ROSA RODRIGUEZ"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS40",piso:"",nom:"Jardín Bancolombia",ev:"HOLLY ANDREA DE LA ROSA RODRIGUEZ"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS28",piso:"",nom:"Jardín Bloque de la Salud",ev:"IRMINA DEL CARMEN RICAURTE MARTINEZ"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS09",piso:"",nom:"Jardín alrededor del Edificio Santo Domingo (Bloque J)",ev:"ISABELLA SIR VALDES"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS12",piso:"",nom:"Jardín Media Torta Coliseo (Frente a Cancha de Tennis)",ev:"ISABELLA SIR VALDES"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS13",piso:"",nom:"Jardín Escaleras Coliseo",ev:"ISABELLA SIR VALDES"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS15",piso:"",nom:"Jardín Casa Estudio",ev:"ISABELLA SIR VALDES"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS17",piso:"",nom:"Jardín Central de Frío 2 (Frente Laboratorios ING Civil atras de Bloque K)",ev:"ISABELLA SIR VALDES"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS18",piso:"",nom:"Jardín Central de Acopio",ev:"ISABELLA SIR VALDES"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS19",piso:"",nom:"Jardín Zona Martillo (Alrededor de la Zona Multiple de Estudiantes 2)",ev:"ISABELLA SIR VALDES"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS21",piso:"",nom:"Jardín Bloque Idiomas 4 (Bloque I4)",ev:"ISABELLA SIR VALDES"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS23",piso:"",nom:"Jardín Emisora (Bloque D)",ev:"ISABELLA SIR VALDES"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS27",piso:"",nom:"Jardín Ptar Principal (Frente a la bodega de mantenimiento)",ev:"ISABELLA SIR VALDES"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS29",piso:"",nom:"Jardín Zona Multiple Estudiantes 1",ev:"ISABELLA SIR VALDES"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS30",piso:"",nom:"Jardín Almacen (Frente a Cancha de Tennis)",ev:"ISABELLA SIR VALDES"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS31",piso:"",nom:"Jardín Coliseo",ev:"ISABELLA SIR VALDES"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS32",piso:"",nom:"Jardín Lobby Norte (Coliseo)",ev:"ISABELLA SIR VALDES"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS11",piso:"",nom:"Jardín Alrededor de la Rampa de Posgrados (Bloque G)",ev:"JOHANNA HELENA MORENO MONTAÑEZ"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS26",piso:"",nom:"Jardín Izquierdo Plazoleta Posgrados (Frente Bloque G)",ev:"JOHANNA HELENA MORENO MONTAÑEZ"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS16",piso:"",nom:"Jardín Portería 04",ev:"JOSE MAURICIO VILLEGAS ROJAS"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS34",piso:"",nom:"Jardín Portería 01",ev:"JOSE MAURICIO VILLEGAS ROJAS"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS35",piso:"",nom:"Jardín Portería 02",ev:"JOSE MAURICIO VILLEGAS ROJAS"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS36",piso:"",nom:"Jardín Campestre (Izquierda de porteria 01)",ev:"JOSE MAURICIO VILLEGAS ROJAS"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS41",piso:"",nom:"Jardín Campos Deportivos",ev:"JUAN CAMILO PERALTA"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS42",piso:"",nom:"Jardínes Bloque M",ev:"JUAN CAMILO PERALTA"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS10",piso:"",nom:"Jardín Café Du Nord",ev:"JUAN CARLOS GALEANO MUÑOZ"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS20",piso:"",nom:"Jardín Bloque K",ev:"JUAN CARLOS GALEANO MUÑOZ"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS22",piso:"",nom:"Jardín KM5 hacia Instituto de Idiomas",ev:"NITZIA GISELA CARABALLO CABRERA"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS24",piso:"",nom:"Jardín Auditorio (Bloque F)",ev:"NITZIA GISELA CARABALLO CABRERA"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS25",piso:"",nom:"Jardín Palmeras 1966 (Frente)",ev:"NITZIA GISELA CARABALLO CABRERA"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS06",piso:"",nom:"Jardín Laboratorio 5",ev:"SAMIRA DEL CARMEN CONSUEGRA BETTER"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS07",piso:"",nom:"Jardín Laboratorio 6",ev:"SAMIRA DEL CARMEN CONSUEGRA BETTER"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS37",piso:"",nom:"Jardín Du Nord Plaza",ev:"SAMIRA DEL CARMEN CONSUEGRA BETTER"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS38",piso:"",nom:"Jardín Graphique",ev:"SAMIRA DEL CARMEN CONSUEGRA BETTER"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS39",piso:"",nom:"Jardín Express",ev:"SAMIRA DEL CARMEN CONSUEGRA BETTER"},
  {cat:"jardin",ed:"CAMPUS",cod:"J-CAMPUS43",piso:"",nom:"Fuente de la Rectitud, Alegría y Verdad",ev:"SAMIRA DEL CARMEN CONSUEGRA BETTER"},
  {cat:"jardin",ed:"FUERA",cod:"J-EXTER05",piso:"",nom:"Jardín Exterior Portería 11 a Portería 11B",ev:"JOSE MAURICIO VILLEGAS ROJAS"},
  {cat:"jardin",ed:"FUERA",cod:"J-EXTER06",piso:"",nom:"Jardín Exterior Portería 05 a Portería 07",ev:"JOSE MAURICIO VILLEGAS ROJAS"},
  {cat:"jardin",ed:"FUERA",cod:"J-EXTER01",piso:"",nom:"Jardín Parqueadero 08-Vía Colegio San José",ev:"JUAN CAMILO PERALTA"},
  {cat:"jardin",ed:"FUERA",cod:"J-EXTER02",piso:"",nom:"Jardín Parqueadero 08",ev:"JUAN CAMILO PERALTA"},
  {cat:"jardin",ed:"FUERA",cod:"J-EXTER03",piso:"",nom:"Jardín Parqueadero 09",ev:"JUAN CAMILO PERALTA"},
  {cat:"jardin",ed:"FUERA",cod:"J-EXTER04",piso:"",nom:"Jardín Parqueadero 12",ev:"JUAN CAMILO PERALTA"},
  {cat:"fachada",ed:"BACA",cod:"BLD-BACA",piso:"",nom:"Casa Estudio Alfredo Correa De Andreis",ev:"JOAQUIN JESUS PINTO ROMERO"},
  {cat:"fachada",ed:"BKCP",cod:"BLD-BKCP",piso:"",nom:"Biblioteca Karl C. Parrish Jr.",ev:"GRACE MARIA SANCHEZ PATERNOSTRO"},
  {cat:"fachada",ed:"BLOQA",cod:"BLD-A",piso:"",nom:"Edificio Bloque A",ev:"HOLLY ANDREA DE LA ROSA RODRIGUEZ"},
  {cat:"fachada",ed:"BLOQB",cod:"BLD-B",piso:"",nom:"Edificio Bloque B",ev:"VIVIANA CARREÑO DURAN"},
  {cat:"fachada",ed:"BLOQC",cod:"BLD-C",piso:"",nom:"Edificio Bloque C",ev:"MARIBEL DEL SOCORRO PEREZ ROMERO"},
  {cat:"fachada",ed:"BLOQD",cod:"BLD-D",piso:"",nom:"Edificio Bloque D",ev:"DIANA CAROLINA CASTRO HERNANDEZ"},
  {cat:"fachada",ed:"BLOQE",cod:"BLD-E",piso:"",nom:"Edificio Bloque E",ev:"SANDRA PAOLA PEÑA CASTELLANO"},
  {cat:"fachada",ed:"BLOQF",cod:"BLD-F",piso:"",nom:"Edificio Bloque F",ev:"SANDRA PAOLA PEÑA CASTELLANO"},
  {cat:"fachada",ed:"BLOQG",cod:"BLD-G",piso:"",nom:"Edificio Álvaro Jaramillo Vengoechea",ev:"IVAN JOSE DE JESUS LUZARDO LUNA"},
  {cat:"fachada",ed:"BLOQI",cod:"BLD-I",piso:"",nom:"Edificio Bloque I",ev:"SANDRA PAOLA PEÑA CASTELLANO"},
  {cat:"fachada",ed:"BLOQJ",cod:"BLD-J",piso:"",nom:"Edificio Mario Santo Domingo",ev:"JUAN CAMILO PERALTA"},
  {cat:"fachada",ed:"BLOQK",cod:"BLD-K",piso:"",nom:"Edificio Bloque K - Ingenierías",ev:"JUAN CARLOS GALEANO MUÑOZ"},
  {cat:"fachada",ed:"BLOQM",cod:"BLD-M",piso:"",nom:"Edificio Bloque M",ev:"Alexander Villegas Mendoza"},
  {cat:"fachada",ed:"COLIS",cod:"BLD-COLIS",piso:"",nom:"Coliseo",ev:"EDWIN LUIS ANGULO LUGO"},
  {cat:"acceso",ed:"CAMPUS",cod:"C-ACCES01",piso:"",nom:"Portería 1",ev:"JOSE MAURICIO VILLEGAS ROJAS"},
  {cat:"acceso",ed:"CAMPUS",cod:"C-ACCES04",piso:"",nom:"Portería 4",ev:"JOSE MAURICIO VILLEGAS ROJAS"},
  {cat:"acceso",ed:"CAMPUS",cod:"C-ACCES07",piso:"",nom:"Portería 7",ev:"JOSE MAURICIO VILLEGAS ROJAS"},
  {cat:"acceso",ed:"CAMPUS",cod:"C-ACCES11",piso:"",nom:"Portería 11",ev:"JOSE MAURICIO VILLEGAS ROJAS"},
  {cat:"acceso",ed:"CAMPUS",cod:"C-ACCES11B",piso:"",nom:"Portería 11B",ev:"JOSE MAURICIO VILLEGAS ROJAS"},
  {cat:"acceso",ed:"CAMPUS",cod:"C-ACCES09",piso:"",nom:"Portería 09 peatonal (hacia bloque M)",ev:"JOSE MAURICIO VILLEGAS ROJAS"},
  {cat:"cancha",ed:"CAMPUS",cod:"PISCINA",piso:"",nom:"Piscina",ev:"Alexander Villegas Mendoza"},
  {cat:"cancha",ed:"CAMPUS",cod:"CAMP-FIELD02",piso:"",nom:"Cancha Multiple cubierta",ev:"EDWIN LUIS ANGULO LUGO"},
  {cat:"cancha",ed:"CAMPUS",cod:"CAMP-FIELD03",piso:"",nom:"Cancha de raquetball 1",ev:"EDWIN LUIS ANGULO LUGO"},
  {cat:"cancha",ed:"CAMPUS",cod:"CAMP-FIELD04",piso:"",nom:"Cancha de raquetball 2",ev:"EDWIN LUIS ANGULO LUGO"},
  {cat:"cancha",ed:"CAMPUS",cod:"CAMP-FIELD05",piso:"",nom:"Cancha de raquetball 3",ev:"EDWIN LUIS ANGULO LUGO"},
  {cat:"cancha",ed:"CAMPUS",cod:"CAMP-FIELD06",piso:"",nom:"Cancha fútbol",ev:"EDWIN LUIS ANGULO LUGO"},
  {cat:"cancha",ed:"CAMPUS",cod:"CAMP-FIELD07",piso:"",nom:"Cancha Tenis 1",ev:"EDWIN LUIS ANGULO LUGO"},
  {cat:"cancha",ed:"CAMPUS",cod:"CAMP-FIELD08",piso:"",nom:"Cancha Tenis 2",ev:"EDWIN LUIS ANGULO LUGO"},
  {cat:"cancha",ed:"CAMPUS",cod:"CAMP-FIELD09",piso:"",nom:"Cancha Multiple 1",ev:"EDWIN LUIS ANGULO LUGO"},
  {cat:"cancha",ed:"CAMPUS",cod:"CAMP-FIELD10",piso:"",nom:"Cancha Multiple 2",ev:"EDWIN LUIS ANGULO LUGO"},
  {cat:"cancha",ed:"CAMPUS",cod:"CAMP-FIELD11",piso:"",nom:"Cancha fútbol sintético",ev:"EDWIN LUIS ANGULO LUGO"},
  {cat:"cancha",ed:"COLIS",cod:"CSEO-FIELD01",piso:"",nom:"Cancha Deportiva",ev:"EDWIN LUIS ANGULO LUGO"},
  {cat:"cafeteria",ed:"BLOQB",cod:"ZONALI11",piso:"1",nom:"Hot Dogs",ev:"VIVIANA CARREÑO DURAN"},
  {cat:"cafeteria",ed:"BLOQF",cod:"ZONALI01",piso:"1",nom:"Du Nord Plaza",ev:"SAMIRA DEL CARMEN CONSUEGRA BETTER"},
  {cat:"cafeteria",ed:"BLOQF",cod:"ZONALI02",piso:"2",nom:"La Crepería",ev:"SAMIRA DEL CARMEN CONSUEGRA BETTER"},
  {cat:"cafeteria",ed:"BLOQF",cod:"ZONALI03",piso:"2",nom:"1966",ev:"SAMIRA DEL CARMEN CONSUEGRA BETTER"},
  {cat:"cafeteria",ed:"BLOQJ",cod:"ZONALI05",piso:"9",nom:"Bocas de Ceniza",ev:"VALERIA MELISSA FONTALVO QUINTERO"},
  {cat:"cafeteria",ed:"BLOQK",cod:"ZONALI04",piso:"4",nom:"Le Petit",ev:"JUAN CARLOS GALEANO MUÑOZ"},
  {cat:"cafeteria",ed:"CAMPUS",cod:"ZONALI07",piso:"",nom:"Café Du Nord",ev:"JUAN CARLOS GALEANO MUÑOZ"},
  {cat:"cafeteria",ed:"CAMPUS",cod:"ZONALI09",piso:"",nom:"La Esquina",ev:"SAMIRA DEL CARMEN CONSUEGRA BETTER"},
  {cat:"cafeteria",ed:"CAMPUS",cod:"ZONALI10",piso:"",nom:"El Express",ev:"SAMIRA DEL CARMEN CONSUEGRA BETTER"},
  {cat:"cafeteria",ed:"CAMPUS",cod:"ZONALI08",piso:"",nom:"El Contenedor",ev:"OSVALDO DE JESUS GAMARRA AMARIS"},
  {cat:"cafeteria",ed:"COLIS",cod:"ZONALI06",piso:"3",nom:"Du Nord Terrasse",ev:"JUAN CAMILO PERALTA"},
  {cat:"biblioteca",ed:"BACA",cod:"SAES08",piso:"1",nom:"Sala de Estudio BACA",ev:"JOAQUIN JESUS PINTO ROMERO"},
  {cat:"biblioteca",ed:"BACA",cod:"SAES09",piso:"2",nom:"Sala de Estudio BACA",ev:"JOAQUIN JESUS PINTO ROMERO"},
  {cat:"biblioteca",ed:"BACA",cod:"SAES10",piso:"3",nom:"Sala de Estudio BACA",ev:"JOAQUIN JESUS PINTO ROMERO"},
  {cat:"biblioteca",ed:"BKCP",cod:"SAES11",piso:"S",nom:"Sala de Estudio BKCP",ev:"GRACE MARIA SANCHEZ PATERNOSTRO"},
  {cat:"biblioteca",ed:"BKCP",cod:"SAES12",piso:"1",nom:"Sala de Estudio BKCP",ev:"GRACE MARIA SANCHEZ PATERNOSTRO"},
  {cat:"biblioteca",ed:"BKCP",cod:"SAES13",piso:"2",nom:"Sala de Estudio BKCP",ev:"GRACE MARIA SANCHEZ PATERNOSTRO"},
  {cat:"biblioteca",ed:"BKCP",cod:"SAES14",piso:"3",nom:"Sala de Estudio BKCP",ev:"GRACE MARIA SANCHEZ PATERNOSTRO"},
  {cat:"biblioteca",ed:"BKCP",cod:"SAES15",piso:"4",nom:"Sala de Estudio BKCP",ev:"GRACE MARIA SANCHEZ PATERNOSTRO"},
  {cat:"biblioteca",ed:"BLOQA",cod:"SAES01",piso:"1",nom:"Sala de Estudio BLOQA",ev:"HOLLY ANDREA DE LA ROSA RODRIGUEZ"},
  {cat:"biblioteca",ed:"BLOQB",cod:"SAES02",piso:"1",nom:"Sala de Estudio BLOQB",ev:"VIVIANA CARREÑO DURAN"},
  {cat:"biblioteca",ed:"BLOQD",cod:"SAES03",piso:"1",nom:"Sala de Estudio BLOQD",ev:"DIANA CAROLINA CASTRO HERNANDEZ"},
  {cat:"biblioteca",ed:"BLOQE",cod:"SAES04",piso:"1",nom:"Sala de Estudio BLOQE",ev:"JUAN CARLOS GALEANO MUÑOZ"},
  {cat:"biblioteca",ed:"BLOQG",cod:"SAES05",piso:"1",nom:"Sala de Estudio BLOQG",ev:"LEILA ANGELA MLAYES HADDAD"},
  {cat:"biblioteca",ed:"BLOQJ",cod:"SAES06",piso:"1",nom:"Sala de Estudio BLOQJ",ev:"MARIA ALEJANDRA SOCARRAS MEDRANO"},
  {cat:"biblioteca",ed:"CAMPUS",cod:"ZOEST01",piso:"1",nom:"Zona de Estudiantes - Bambú 1",ev:"ELMA CRISTINA MORALES CORTINA"},
  {cat:"biblioteca",ed:"CAMPUS",cod:"ZOEST02",piso:"1",nom:"Zona de Estudiantes - Bambú 2",ev:"ELMA CRISTINA MORALES CORTINA"},
  {cat:"biblioteca",ed:"L1",cod:"SAES07",piso:"1",nom:"Sala de Estudio Bloque Laboratorio N° 1",ev:"JOHANNA HELENA MORENO MONTAÑEZ"},
  {cat:"bano",ed:"1L6",cod:"BATH77",piso:"",nom:"Baño Hombres Bloque Laboratorios N° 6",ev:"MARIA AUXILIADORA HEMER NARVAEZ"},
  {cat:"bano",ed:"1L6",cod:"BATH78",piso:"",nom:"Baño Hombres Bloque Laboratorios N° 6",ev:"MARIA AUXILIADORA HEMER NARVAEZ"},
  {cat:"bano",ed:"1L6",cod:"BATH79",piso:"",nom:"Baño Hombres Bloque Laboratorios N° 6",ev:"MARIA AUXILIADORA HEMER NARVAEZ"},
  {cat:"bano",ed:"1L6",cod:"BATH80",piso:"",nom:"Baño Mujeres Bloque Laboratorios N° 6",ev:"MARIA AUXILIADORA HEMER NARVAEZ"},
  {cat:"bano",ed:"1L6",cod:"BATH81",piso:"",nom:"Baño Mujeres Bloque Laboratorios N° 6",ev:"MARIA AUXILIADORA HEMER NARVAEZ"},
  {cat:"bano",ed:"1L6",cod:"BATH82",piso:"",nom:"Baño Mujeres Bloque Laboratorios N° 6",ev:"MARIA AUXILIADORA HEMER NARVAEZ"},
  {cat:"bano",ed:"BACA",cod:"BATH83",piso:"1",nom:"Baño Hombres Casa Estudio - Piso 1",ev:"JOAQUIN JESUS PINTO ROMERO"},
  {cat:"bano",ed:"BACA",cod:"BATH84",piso:"2",nom:"Baño Hombres Casa Estudio - Piso 2",ev:"JOAQUIN JESUS PINTO ROMERO"},
  {cat:"bano",ed:"BACA",cod:"BATH85",piso:"3",nom:"Baño Hombres Casa Estudio - Piso 3",ev:"JOAQUIN JESUS PINTO ROMERO"},
  {cat:"bano",ed:"BACA",cod:"BATH86",piso:"1",nom:"Baño Mujeres Casa Estudio - Piso 1",ev:"JOAQUIN JESUS PINTO ROMERO"},
  {cat:"bano",ed:"BACA",cod:"BATH87",piso:"2",nom:"Baño Mujeres Casa Estudio - Piso 2",ev:"JOAQUIN JESUS PINTO ROMERO"},
  {cat:"bano",ed:"BACA",cod:"BATH88",piso:"3",nom:"Baño Mujeres Casa Estudio - Piso 3",ev:"JOAQUIN JESUS PINTO ROMERO"},
  {cat:"bano",ed:"BKCP",cod:"BATH92",piso:"S",nom:"Baño Mujeres Biblioteca - Piso 1",ev:"GRACE MARIA SANCHEZ PATERNOSTRO"},
  {cat:"bano",ed:"BKCP",cod:"BATH93",piso:"1",nom:"Baño Mujeres Biblioteca - Piso 2",ev:"GRACE MARIA SANCHEZ PATERNOSTRO"},
  {cat:"bano",ed:"BKCP",cod:"BATH94",piso:"2",nom:"Baño Mujeres Biblioteca - Piso 3",ev:"GRACE MARIA SANCHEZ PATERNOSTRO"},
  {cat:"bano",ed:"BKCP",cod:"BATH89",piso:"S",nom:"Baño Hombres Biblioteca - Piso 1",ev:"JOAQUIN JESUS PINTO ROMERO"},
  {cat:"bano",ed:"BKCP",cod:"BATH90",piso:"1",nom:"Baño Hombres Biblioteca - Piso 2",ev:"JOAQUIN JESUS PINTO ROMERO"},
  {cat:"bano",ed:"BKCP",cod:"BATH91",piso:"2",nom:"Baño Hombres Biblioteca - Piso 3",ev:"JOAQUIN JESUS PINTO ROMERO"},
  {cat:"bano",ed:"BLOQA",cod:"BATH01",piso:"2",nom:"Baño Hombres BLOQA - Piso 2",ev:"HOLLY ANDREA DE LA ROSA RODRIGUEZ"},
  {cat:"bano",ed:"BLOQA",cod:"BATH02",piso:"2",nom:"Baño Mujeres BLOQA - Piso 2",ev:"HOLLY ANDREA DE LA ROSA RODRIGUEZ"},
  {cat:"bano",ed:"BLOQB",cod:"BATH03",piso:"1",nom:"Baño Hombres BLOQB - Piso 1",ev:"VIVIANA CARREÑO DURAN"},
  {cat:"bano",ed:"BLOQB",cod:"BATH04",piso:"1",nom:"Baño Mujeres BLOQB - Piso 1",ev:"VIVIANA CARREÑO DURAN"},
  {cat:"bano",ed:"BLOQC",cod:"BATH05",piso:"2",nom:"Baño Hombres BLOQC - Piso 2",ev:"MARIBEL DEL SOCORRO PEREZ ROMERO"},
  {cat:"bano",ed:"BLOQC",cod:"BATH06",piso:"2",nom:"Baño Mujeres BLOQC - Piso 2",ev:"MARIBEL DEL SOCORRO PEREZ ROMERO"},
  {cat:"bano",ed:"BLOQE",cod:"BATH07",piso:"1",nom:"Baño Hombres BLOQE - Piso 1",ev:"ANGELA MERCEDES GONZALEZ VERGARA"},
  {cat:"bano",ed:"BLOQE",cod:"BATH08",piso:"2",nom:"Baño Mujeres BLOQE - Piso 2",ev:"ANGELA MERCEDES GONZALEZ VERGARA"},
  {cat:"bano",ed:"BLOQF",cod:"BATH09",piso:"2",nom:"Baño Hombres BLOQF - Piso 2",ev:"NITZIA GISELA CARABALLO CABRERA"},
  {cat:"bano",ed:"BLOQF",cod:"BATH10",piso:"2",nom:"Baño Mujeres BLOQF - Piso 2",ev:"NITZIA GISELA CARABALLO CABRERA"},
  {cat:"bano",ed:"BLOQG",cod:"BATH11",piso:"1",nom:"Baño Hombres BLOQG - Piso 1",ev:"IVAN JOSE DE JESUS LUZARDO LUNA"},
  {cat:"bano",ed:"BLOQG",cod:"BATH12",piso:"2",nom:"Baño Hombres BLOQG - Piso 2",ev:"IVAN JOSE DE JESUS LUZARDO LUNA"},
  {cat:"bano",ed:"BLOQG",cod:"BATH13",piso:"3",nom:"Baño Hombres BLOQG - Piso 3",ev:"IVAN JOSE DE JESUS LUZARDO LUNA"},
  {cat:"bano",ed:"BLOQG",cod:"BATH14",piso:"4",nom:"Baño Hombres BLOQG - Piso 4",ev:"IVAN JOSE DE JESUS LUZARDO LUNA"},
  {cat:"bano",ed:"BLOQG",cod:"BATH15",piso:"5",nom:"Baño Hombres BLOQG - Piso 5",ev:"IVAN JOSE DE JESUS LUZARDO LUNA"},
  {cat:"bano",ed:"BLOQG",cod:"BATH16",piso:"1",nom:"Baño Mujeres BLOQG - Piso 1",ev:"LEILA ANGELA MLAYES HADDAD"},
  {cat:"bano",ed:"BLOQG",cod:"BATH17",piso:"2",nom:"Baño Mujeres BLOQG - Piso 2",ev:"LEILA ANGELA MLAYES HADDAD"},
  {cat:"bano",ed:"BLOQG",cod:"BATH18",piso:"3",nom:"Baño Mujeres BLOQG - Piso 3",ev:"LEILA ANGELA MLAYES HADDAD"},
  {cat:"bano",ed:"BLOQG",cod:"BATH19",piso:"4",nom:"Baño Mujeres BLOQG - Piso 4",ev:"LEILA ANGELA MLAYES HADDAD"},
  {cat:"bano",ed:"BLOQG",cod:"BATH20",piso:"5",nom:"Baño Mujeres BLOQG - Piso 5",ev:"LEILA ANGELA MLAYES HADDAD"},
  {cat:"bano",ed:"BLOQI",cod:"BATH21",piso:"1",nom:"Baño Hombre BLOQI1 - Piso 1",ev:"ANA KARINA QUINTERO ARTEAGA"},
  {cat:"bano",ed:"BLOQI",cod:"BATH22",piso:"1",nom:"Baño Mujeres BLOQI1 - Piso 1",ev:"ANA KARINA QUINTERO ARTEAGA"},
  {cat:"bano",ed:"BLOQI",cod:"BATH23",piso:"2",nom:"Baño Hombres BLOQI4 - Piso 2",ev:"ANA KARINA QUINTERO ARTEAGA"},
  {cat:"bano",ed:"BLOQI",cod:"BATH24",piso:"2",nom:"Baño Mujeres BLOQI4 - Piso 2",ev:"ANA KARINA QUINTERO ARTEAGA"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH49",piso:"1",nom:"Baño Hombres BLOQJ - Piso 1",ev:"DANIEL EDUARDO GUTIERREZ BORRERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH59",piso:"1",nom:"Baño Mujeres BLOQJ - Piso 1",ev:"DANIEL EDUARDO GUTIERREZ BORRERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH50",piso:"2",nom:"Baño Hombres BLOQJ - Piso 2",ev:"DANIEL EDUARDO GUTIERREZ BORRERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH60",piso:"2",nom:"Baño Mujeres BLOQJ - Piso 2",ev:"DANIEL EDUARDO GUTIERREZ BORRERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH51",piso:"3",nom:"Baño Hombres BLOQJ - Piso 3",ev:"DANIEL EDUARDO GUTIERREZ BORRERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH61",piso:"3",nom:"Baño Mujeres BLOQJ - Piso 3",ev:"DANIEL EDUARDO GUTIERREZ BORRERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH52",piso:"4",nom:"Baño Hombres BLOQJ - Piso 4",ev:"DANIEL EDUARDO GUTIERREZ BORRERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH62",piso:"4",nom:"Baño Mujeres BLOQJ - Piso 4",ev:"DANIEL EDUARDO GUTIERREZ BORRERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH53",piso:"5",nom:"Baño Hombres BLOQJ - Piso 5",ev:"DANIEL EDUARDO GUTIERREZ BORRERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH63",piso:"5",nom:"Baño Mujeres BLOQJ - Piso 5",ev:"DANIEL EDUARDO GUTIERREZ BORRERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH54",piso:"6",nom:"Baño Hombres BLOQJ - Piso 6",ev:"DANIEL EDUARDO GUTIERREZ BORRERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH64",piso:"6",nom:"Baño Mujeres BLOQJ - Piso 6",ev:"DANIEL EDUARDO GUTIERREZ BORRERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH55",piso:"7",nom:"Baño Hombres BLOQJ - Piso 7",ev:"VALERIA MELISSA FONTALVO QUINTERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH65",piso:"7",nom:"Baño Mujeres BLOQJ - Piso 7",ev:"VALERIA MELISSA FONTALVO QUINTERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH56",piso:"8",nom:"Baño Hombres BLOQJ - Piso 8",ev:"VALERIA MELISSA FONTALVO QUINTERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH66",piso:"8",nom:"Baño Mujeres BLOQJ - Piso 8",ev:"VALERIA MELISSA FONTALVO QUINTERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH57",piso:"9",nom:"Baño Hombres BLOQJ - Piso 9",ev:"VALERIA MELISSA FONTALVO QUINTERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH67",piso:"9",nom:"Baño Mujeres BLOQJ - Piso 9",ev:"VALERIA MELISSA FONTALVO QUINTERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH58",piso:"10",nom:"Baño Hombres BLOQJ - Piso 10",ev:"VALERIA MELISSA FONTALVO QUINTERO"},
  {cat:"bano",ed:"BLOQJ",cod:"BATH68",piso:"10",nom:"Baño Mujeres BLOQJ - Piso 10",ev:"VALERIA MELISSA FONTALVO QUINTERO"},
  {cat:"bano",ed:"BLOQK",cod:"BATH34",piso:"1",nom:"Baño Mujeres BLOQK - Piso 1",ev:"ANA KARINA QUINTERO ARTEAGA"},
  {cat:"bano",ed:"BLOQK",cod:"BATH35",piso:"2",nom:"Baño Mujeres BLOQK - Piso 2",ev:"ANA KARINA QUINTERO ARTEAGA"},
  {cat:"bano",ed:"BLOQK",cod:"BATH36",piso:"3",nom:"Baño Mujeres BLOQK - Piso 3",ev:"ANA KARINA QUINTERO ARTEAGA"},
  {cat:"bano",ed:"BLOQK",cod:"BATH37",piso:"4",nom:"Baño Mujeres BLOQK - Piso 4",ev:"ANA KARINA QUINTERO ARTEAGA"},
  {cat:"bano",ed:"BLOQK",cod:"BATH38",piso:"5",nom:"Baño Mujeres BLOQK - Piso 5",ev:"ANA KARINA QUINTERO ARTEAGA"},
  {cat:"bano",ed:"BLOQK",cod:"BATH39",piso:"6",nom:"Baño Mujeres BLOQK - Piso 6",ev:"ANA KARINA QUINTERO ARTEAGA"},
  {cat:"bano",ed:"BLOQK",cod:"BATH40",piso:"7",nom:"Baño Mujeres BLOQK - Piso 7",ev:"ANA KARINA QUINTERO ARTEAGA"},
  {cat:"bano",ed:"BLOQK",cod:"BATH41",piso:"8",nom:"Baño Mujeres BLOQK - Piso 8",ev:"ANA KARINA QUINTERO ARTEAGA"},
  {cat:"bano",ed:"BLOQK",cod:"BATH42",piso:"9",nom:"Baño Mujeres BLOQK - Piso 9",ev:"ANA KARINA QUINTERO ARTEAGA"},
  {cat:"bano",ed:"BLOQK",cod:"BATH25",piso:"1",nom:"Baño Hombres BLOQK - Piso 1",ev:"OSVALDO DE JESUS GAMARRA AMARIS"},
  {cat:"bano",ed:"BLOQK",cod:"BATH26",piso:"2",nom:"Baño Hombres BLOQK - Piso 2",ev:"OSVALDO DE JESUS GAMARRA AMARIS"},
  {cat:"bano",ed:"BLOQK",cod:"BATH27",piso:"3",nom:"Baño Hombres BLOQK - Piso 3",ev:"OSVALDO DE JESUS GAMARRA AMARIS"},
  {cat:"bano",ed:"BLOQK",cod:"BATH28",piso:"4",nom:"Baño Hombres BLOQK - Piso 4",ev:"OSVALDO DE JESUS GAMARRA AMARIS"},
  {cat:"bano",ed:"BLOQK",cod:"BATH29",piso:"5",nom:"Baño Hombres BLOQK - Piso 5",ev:"OSVALDO DE JESUS GAMARRA AMARIS"},
  {cat:"bano",ed:"BLOQK",cod:"BATH30",piso:"6",nom:"Baño Hombres BLOQK - Piso 6",ev:"OSVALDO DE JESUS GAMARRA AMARIS"},
  {cat:"bano",ed:"BLOQK",cod:"BATH31",piso:"7",nom:"Baño Hombres BLOQK - Piso 7",ev:"OSVALDO DE JESUS GAMARRA AMARIS"},
  {cat:"bano",ed:"BLOQK",cod:"BATH32",piso:"8",nom:"Baño Hombres BLOQK - Piso 8",ev:"OSVALDO DE JESUS GAMARRA AMARIS"},
  {cat:"bano",ed:"BLOQK",cod:"BATH33",piso:"9",nom:"Baño Hombres BLOQK - Piso 9",ev:"OSVALDO DE JESUS GAMARRA AMARIS"},
  {cat:"bano",ed:"BLOQM",cod:"BATH43",piso:"1",nom:"Baño Hombres BLOQM",ev:"Alexander Villegas Mendoza"},
  {cat:"bano",ed:"BLOQM",cod:"BATH44",piso:"1",nom:"Baño Hombres BLOQM",ev:"Alexander Villegas Mendoza"},
  {cat:"bano",ed:"BLOQM",cod:"BATH45",piso:"1",nom:"Baño Hombres BLOQM",ev:"Alexander Villegas Mendoza"},
  {cat:"bano",ed:"BLOQM",cod:"BATH46",piso:"1",nom:"Baño Mujeres BLOQM",ev:"Alexander Villegas Mendoza"},
  {cat:"bano",ed:"BLOQM",cod:"BATH47",piso:"1",nom:"Baño Mujeres BLOQM",ev:"Alexander Villegas Mendoza"},
  {cat:"bano",ed:"BLOQM",cod:"BATH48",piso:"1",nom:"Baño Mujeres BLOQM",ev:"Alexander Villegas Mendoza"},
  {cat:"bano",ed:"COLIS",cod:"BATH95",piso:"1",nom:"Baño Hombres Coliseo",ev:"JUAN CAMILO PERALTA"},
  {cat:"bano",ed:"COLIS",cod:"BATH96",piso:"1",nom:"Baño Mujeres Coliseo",ev:"MILENA MERCEDES VARELA CARDONA"},
  {cat:"bano",ed:"L4",cod:"BATH69",piso:"",nom:"Baño Hombres Bloque Laboratorios N° 4",ev:"MARIA AUXILIADORA HEMER NARVAEZ"},
  {cat:"bano",ed:"L4",cod:"BATH70",piso:"",nom:"Baño Hombres Bloque Laboratorios N° 4",ev:"MARIA AUXILIADORA HEMER NARVAEZ"},
  {cat:"bano",ed:"L4",cod:"BATH71",piso:"",nom:"Baño Hombres Bloque Laboratorios N° 4",ev:"MARIA AUXILIADORA HEMER NARVAEZ"},
  {cat:"bano",ed:"L4",cod:"BATH72",piso:"",nom:"Baño Mujeres Bloque Laboratorios N° 4",ev:"MARIA AUXILIADORA HEMER NARVAEZ"},
  {cat:"bano",ed:"L4",cod:"BATH73",piso:"",nom:"Baño Mujeres Bloque Laboratorios N° 4",ev:"MARIA AUXILIADORA HEMER NARVAEZ"},
  {cat:"bano",ed:"L4",cod:"BATH74",piso:"",nom:"Baño Mujeres Bloque Laboratorios N° 4",ev:"MARIA AUXILIADORA HEMER NARVAEZ"},
  {cat:"bano",ed:"L5",cod:"BATH75",piso:"1",nom:"Baño Hombres Bloque Laboratorios N° 5",ev:"MARIA AUXILIADORA HEMER NARVAEZ"},
  {cat:"bano",ed:"L5",cod:"BATH76",piso:"1",nom:"Baño Mujeres Bloque Laboratorios N° 5",ev:"MARIA AUXILIADORA HEMER NARVAEZ"},
];

// Lista de evaluadores extraída de la columna 'Evaluador/a'
const EVALUADORES = [
  "ANA KARINA QUINTERO ARTEAGA",
  "ANGELA MERCEDES GONZALEZ VERGARA",
  "Alexander Villegas Mendoza",
  "CESAR MANUEL STAND ZAMBRANO",
  "DANIEL EDUARDO GUTIERREZ BORRERO",
  "DIANA CAROLINA CASTRO HERNANDEZ",
  "EDWIN LUIS ANGULO LUGO",
  "ELMA CRISTINA MORALES CORTINA",
  "EYLEEN GIOBET CASTILLO MENDOZA",
  "GRACE MARIA SANCHEZ PATERNOSTRO",
  "GUSTAVO ADOLFO LOPEZ HENRIQUEZ",
  "HAROLD JOSE RIOS BRUGES",
  "HOLLY ANDREA DE LA ROSA RODRIGUEZ",
  "Hailyn Kelly Mejia Piedris",
  "IRMINA DEL CARMEN RICAURTE MARTINEZ",
  "ISABELLA SIR VALDES",
  "IVAN JOSE DE JESUS LUZARDO LUNA",
  "JOAQUIN JESUS PINTO ROMERO",
  "JOHANNA HELENA MORENO MONTAÑEZ",
  "JOSE MAURICIO VILLEGAS ROJAS",
  "JUAN CAMILO PERALTA",
  "JUAN CARLOS GALEANO MUÑOZ",
  "JULIO ALFREDO JIMENEZ MARTINEZ",
  "LEILA ANGELA MLAYES HADDAD",
  "MARGARITA ROSA DE ALBA AVENDAÑO",
  "MARIA ALEJANDRA SOCARRAS MEDRANO",
  "MARIA AUXILIADORA HEMER NARVAEZ",
  "MARIBEL DEL SOCORRO PEREZ ROMERO",
  "MELISSA DEL CARMEN DELUQUE BASTIDAS",
  "MILENA MERCEDES VARELA CARDONA",
  "NITZIA GISELA CARABALLO CABRERA",
  "OSVALDO DE JESUS GAMARRA AMARIS",
  "PATRICIA JAIMES TABOADA",
  "SAMIRA DEL CARMEN CONSUEGRA BETTER",
  "SANDRA PAOLA PEÑA CASTELLANO",
  "VALERIA MELISSA FONTALVO QUINTERO",
  "VIVIANA CARREÑO DURAN",
  "YOSIRIS YOHANA YEPES MIRANDA",
  "YULEINE YANIET MORENO FONTALVO",
];

// ============================================================
// data.js — Datos de la rúbrica de infraestructura UniNorte
// 13 categorías con dimensiones y descriptores por nivel
// ============================================================

const CATEGORIES = [
  {
    id: "salon", name: "Salón de Clases", icon: "🏫",
    dimensions: [
      { id: "estructura", name: "Estructura y Acabados", descriptors: {
        5: "Paredes, puerta, piso y techo en excelentes condiciones. Pintura uniforme, sin manchas ni grietas. Piso limpio.",
        4: "Paredes, puerta y piso en buen estado general. Marcas menores de uso. Pintura con desgaste mínimo.",
        3: "Pintura desgastada en algunas áreas. Grietas superficiales visibles. Piso con desgaste moderado.",
        2: "Humedad visible, descascaramiento de pintura o grietas notorias. Piso deteriorado.",
        1: "Daño estructural evidente (infiltraciones activas, grietas profundas, techo con riesgo). Piso inestable."
      }},
      { id: "mobiliario", name: "Mobiliario", descriptors: {
        5: "Todo el mobiliario en excelente estado, completo y funcional. Sillas y mesas estables, tableros limpios.",
        4: "Mobiliario en buen estado. Desgaste menor por uso normal. Todos los puestos funcionales.",
        3: "Algunos muebles con desgaste visible. 90%+ de los puestos funcionales.",
        2: "Mobiliario deteriorado: sillas rotas, mesas inestables, tableros dañados. 70-89% funcional.",
        1: "Más del 30% del mobiliario inutilizable. Impide el desarrollo normal de la clase."
      }},
      { id: "iluminacion", name: "Iluminación", descriptors: {
        5: "Iluminación uniforme y suficiente. Todas las luminarias funcionando. Blackouts y/o persianas funcionando correctamente",
        4: "Iluminación adecuada. Máximo 1-2 luminarias fundidas sin afectar significativamente.",
        3: "Iluminación desigual. Algunas zonas oscuras. 10-25% de luminarias sin funcionar.",
        2: "Iluminación insuficiente que dificulta lectura. >25% luminarias sin funcionar.",
        1: "Sin iluminación artificial funcional o extremadamente deficiente."
      }},
      { id: "ventilacion", name: "Ventilación y Climatización", descriptors: {
        5: "AC funcionando a temperatura confortable. Sin ruido.",
        4: "Climatización funcional. Ruido leve.",
        3: "AC funciona con deficiencias (enfría irregularmente, gotea levemente, ruido moderado).",
        2: "Climatización deficiente: no enfría adecuadamente, goteo constante, ruido excesivo.",
        1: "Sin AC funcional en espacio cerrado. Se siente caliente."
      }},
      { id: "tecnologia", name: "Equipos Tecnológicos", descriptors: {
        5: "Computador, Video beam, sonido, tomas eléctricas y conectividad WiFi/ethernet perfectos.",
        4: "Equipos funcionales con detalles menores (cables desordenados a la vista, teclado con letras desgastadas).",
        3: "Algún equipo intermitente. Al menos computador y video beam funcionan.",
        2: "Equipos principales sin funcionar (computador o video beam dañado). Tomas dañadas.",
        1: "Sin equipos tecnológicos funcionales. Sin tomas eléctricas. Sin conectividad."
      }},
      { id: "limpieza", name: "Limpieza e Higiene", descriptors: {
        5: "Espacio impecable. Sin basura, polvo o manchas. Papelera disponible.",
        4: "Limpio en general. Mínimo polvo. Papelera disponible.",
        3: "Limpieza aceptable con acumulación menor de polvo o basura.",
        2: "Suciedad visible en pisos, mesas o sillas. Papelera desbordada o ausente.",
        1: "Espacio sucio. Malos olores, plagas o residuos orgánicos."
      }},
      { id: "senalizacion", name: "Señalización y Accesibilidad", descriptors: {
        5: "Número de salón visible. Señalización de emergencia completa. Acceso para movilidad reducida. Ruta evacuación clara.",
        4: "Señalización presente y legible. Ruta de evacuación visible. Acceso adecuado.",
        3: "Señalización parcial (falta número de sala o señalización incompleta).",
        2: "Señalización ausente o ilegible. Sin ruta de evacuación visible. Obstáculos.",
        1: "Sin señalización. Barreras de accesibilidad significativas. Salidas bloqueadas."
      }}
    ]
  },
  {
    id: "laboratorio", name: "Laboratorio", icon: "🔬",
    dimensions: [
      { id: "estructura", name: "Estructura y Acabados", descriptors: {
        5: "Pisos en excelente estado. Paredes lavables sin daños. Mesones íntegros. Instalaciones de agua/gas seguras.",
        4: "Estructura en buen estado. Desgaste mínimo en superficies. Instalaciones funcionales.",
        3: "Superficies con desgaste moderado (manchas, rayones). Instalaciones funcionales con humedad o goteos menores.",
        2: "Mesones deteriorados o inestables. Pisos resbalosos. Instalaciones con fugas visibles.",
        1: "Daño estructural que compromete la seguridad. Instalaciones de agua/gas con riesgo de accidente."
      }},
      { id: "equipos", name: "Equipos y Dotación", descriptors: {
        5: "Equipos completos, calibrados y en perfecto funcionamiento. Inventario actualizado. Insumos suficientes.",
        4: "Equipos funcionales con mantenimiento preventivo al día. Insumos disponibles.",
        3: "Algunos equipos requieren calibración o reparación menor. Insumos limitados pero suficientes.",
        2: "Equipos clave fuera de servicio. Insumos insuficientes. Prácticas afectadas.",
        1: "Mayoría de equipos inoperativos o ausentes. Imposibilidad de realizar prácticas."
      }},
      { id: "seguridad", name: "Seguridad", descriptors: {
        5: "Ducha de emergencia y lavaojos funcionales (si aplica). Extintores vigentes. Botiquín completo. EPP disponible. Hojas SDS actualizadas. Insumos correctamente almacenados.",
        4: "Elementos de seguridad presentes y funcionales. EPP disponible con desgaste menor. Algunos insumos no están debidamente almacenados.",
        3: "Elementos presentes pero con deficiencias menores (botiquín incompleto, EPP desgastado). Almacenamiento de insumos inadecuado o insuficiente.",
        2: "Faltan elementos críticos (sin extintor, ducha bloqueada). EPP insuficiente o deteriorado. El mal almacenamiento de insumos genera riesgos.",
        1: "Sin elementos de seguridad funcionales. Riesgo inminente. Sustancias peligrosas sin control. No hay almacenamiento de insumos."
      }},
      { id: "ventilacion", name: "Ventilación y Extracción", descriptors: {
        5: "Sistema de extracción/campanas funcionando óptimamente. Ventilación adecuada. Sin olores químicos residuales.",
        4: "Sistemas funcionales con mantenimiento al día. Extracción efectiva con ruido leve.",
        3: "Ventilación funcional pero insuficiente en alta demanda. Olores químicos leves ocasionales.",
        2: "Campanas deficientes o parcialmente inoperativas. Olores químicos persistentes.",
        1: "Sin sistema de extracción funcional. Riesgo de exposición a vapores tóxicos."
      }},
      { id: "limpieza_senal", name: "Limpieza, Iluminación y Señalización", descriptors: {
        5: "Limpieza impecable. Iluminación adecuada. Señalización de riesgos completa (pictogramas GHS, rutas, normas).",
        4: "Limpio y bien iluminado. Señalización presente y legible.",
        3: "Limpieza aceptable. Iluminación adecuada con zonas de penumbra. Señalización parcial.",
        2: "Residuos químicos sin limpiar (si aplica). Iluminación deficiente. Señalización incompleta.",
        1: "Condiciones antihigiénicas. Sin iluminación adecuada. Sin señalización de riesgos."
      }}
    ]
  },
  {
    id: "sala_pc", name: "Sala de Computadores", icon: "💻",
    dimensions: [
      { id: "mobiliario", name: "Mobiliario y Ergonomía", descriptors: {
        5: "Mesas amplias y estables. Sillas ergonómicas. Monitores a altura adecuada. Cableado canalizado.",
        4: "Mobiliario en buen estado. Ergonomía aceptable. Cableado mayormente organizado.",
        3: "Mobiliario funcional con desgaste. Algunos cables expuestos de manera desordenada. Espacio algo reducido entre puestos.",
        2: "Mobiliario deteriorado. Cables desordenados (riesgo de tropiezo). Hacinamiento.",
        1: "Mobiliario inservible. Cableado peligroso. Impide el uso adecuado."
      }},
      { id: "equipos_computo", name: "Equipos de Cómputo", descriptors: {
        5: "100% equipos funcionales. Periféricos completos.",
        4: "95%+ equipos funcionales. Hardware adecuado. Periféricos completos.",
        3: "85-94% equipos funcionales. Rendimiento lento pero utilizable. Algunos periféricos faltantes.",
        2: "70-84% equipos funcionales. Periféricos incompletos.",
        1: "<70% equipos funcionales. Equipos inoperativos."
      }},
      { id: "clima_ilum", name: "Climatización, Iluminación y Limpieza", descriptors: {
        5: "AC funcionando a temperatura confortable. Sin ruido. Iluminación completa. Espacio limpio y sin polvo en equipos.",
        4: "Climatización adecuada. Alguna luminarias sin funcionar pero no afectan significativamente. Limpieza general buena.",
        3: "Climatización funcional con variaciones. Reflejos ocasionales. Polvo acumulado en algunos equipos.",
        2: "Disconfort térmico. Iluminación que genera fatiga visual. Polvo excesivo.",
        1: "Sin climatización. Iluminación deficiente. Suciedad generalizada."
      }}
    ]
  },
  {
    id: "fachada", name: "Fachada de Edificio", icon: "🏢",
    dimensions: [
      { id: "pintura", name: "Pintura y Revestimiento", descriptors: {
        5: "Pintura/revestimiento uniforme, sin descascaramiento ni decoloración. Colores institucionales definidos.",
        4: "Pintura en buen estado con decoloración mínima por exposición solar. Sin descascaramiento.",
        3: "Decoloración moderada. Zonas con pintura desgastada pero sin descascaramiento extenso.",
        2: "Descascaramiento visible. Manchas de humedad notorias. Pérdida de color institucional.",
        1: "Fachada severamente deteriorada. Descascaramiento extenso, grafitis sin remover."
      }},
      { id: "integridad", name: "Integridad Estructural Visible", descriptors: {
        5: "Sin grietas, fisuras ni desprendimientos. Juntas y sellos en perfecto estado.",
        4: "Fisuras superficiales sin implicación estructural. Juntas en buen estado.",
        3: "Grietas superficiales visibles. Sin riesgo estructural aparente.",
        2: "Grietas significativas. Elementos decorativos desprendidos.",
        1: "Grietas estructurales evidentes. Riesgo de desprendimiento. Peligro para transeúntes."
      }},
      { id: "ventaneria", name: "Ventanería y Elementos Exteriores", descriptors: {
        5: "Ventanas limpias, sellos intactos, vidrios completos. Canaletas funcionales. Sin corrosión.",
        4: "Ventanas en buen estado con suciedad menor. Canaletas funcionales. Oxidación mínima.",
        3: "Ventanas con sellos deteriorados. Canaletas con obstrucciones parciales. Oxidación visible.",
        2: "Vidrios rotos o faltantes. Canaletas dañadas que generan humedades. Corrosión avanzada.",
        1: "Ventanería severamente dañada. Drenaje inoperante. Elementos con riesgo de desprendimiento."
      }},
      { id: "aspecto", name: "Limpieza y Aspecto General", descriptors: {
        5: "Fachada impecable. Sin telarañas, nidos ni manchas de agua. Aspecto institucional impecable.",
        4: "Fachada limpia con suciedad menor en zonas poco visibles.",
        3: "Suciedad acumulada visible. Telarañas en esquinas. Manchas de agua en zonas bajas.",
        2: "Fachada visiblemente sucia. Moho o algas en zonas húmedas. Aspecto descuidado.",
        1: "Fachada extremadamente sucia. Crecimiento vegetal invasivo. Impacto negativo en imagen."
      }}
    ]
  },
  {
    id: "cancha", name: "Espacios Deportivos", icon: "⚽",
    dimensions: [
      { id: "superficie", name: "Superficie de Juego", descriptors: {
        5: "Superficie en excelente estado. Demarcación completa y visible. Está nivelado.",
        4: "Superficie en buen estado. Desgaste menor en zonas de alto tráfico. Demarcación legible.",
        3: "Desgaste moderado. Parches irregulares o fisuras menores. Demarcación parcialmente borrada.",
        2: "Superficie deteriorada (huecos, grietas extensas). Demarcación ilegible. Charcos tras lluvia.",
        1: "Superficie inutilizable. Riesgo de lesiones por irregularidades graves. Sin demarcación."
      }},
      { id: "equipamiento", name: "Equipamiento Deportivo", descriptors: {
        5: "Arcos, mallas, tableros y postes completos, firmes y en excelente estado. Graderías seguras.",
        4: "Equipamiento completo y funcional con desgaste menor. Graderías en buen estado.",
        3: "Equipamiento funcional con detalles (mallas rotas parcialmente, tableros desgastados).",
        2: "Equipamiento incompleto o dañado (arcos sin malla, tableros rotos). Graderías con daños.",
        1: "Sin equipamiento o completamente inservible. Graderías inseguras."
      }},
      { id: "ilum_drenaje", name: "Iluminación, Drenaje y Servicios", descriptors: {
        5: "Iluminación nocturna completa. Drenaje no obstaculizado. Bebederos y baños cercanos.",
        4: "Iluminación funcional. Drenaje adecuado. Servicios complementarios disponibles (lockers, disponible, graderías).",
        3: "Iluminación parcial. Drenaje lento pero funcional. Servicios limitados.",
        2: "Iluminación insuficiente para uso nocturno. Encharcamientos frecuentes. Sin servicios.",
        1: "Sin iluminación. Sin drenaje (inundación frecuente). Sin servicios."
      }},
      { id: "seguridad_cerr", name: "Seguridad y Cerramientos", descriptors: {
        5: "Cerramientos/mallas perimetrales completos e íntegros. Superficie libre de objetos peligrosos.",
        4: "Cerramientos en buen estado con reparaciones menores. Espacio seguro.",
        3: "Cerramientos con daños parciales (huecos en mallas). Algunos objetos por retirar.",
        2: "Cerramientos significativamente dañados. Elementos peligrosos cerca del área de juego.",
        1: "Sin cerramientos donde se requieren. Riesgo alto de lesiones."
      }}
    ]
  },
  {
    id: "jardin", name: "Jardín / Zona Verde", icon: "🌳",
    dimensions: [
      { id: "vegetacion", name: "Estado de la Vegetación", descriptors: {
        5: "Grama cortada uniformemente. Árboles y arbustos podados. Plantas ornamentales en buen estado.",
        4: "Vegetación cuidada con mantenimiento reciente. Grama uniforme. Árboles saludables.",
        3: "Grama irregular (requiere corte). Arbustos con crecimiento excesivo. Plantas o gramas visiblemente secas.",
        2: "Grama muy crecida o con zonas secas extensas. Ramas secas sin podar. Plantas muertas.",
        1: "Vegetación abandonada. Maleza invasiva. Árboles con riesgo de caída. Descuido total."
      }},
      { id: "mobiliario_ext", name: "Mobiliario Exterior y Senderos", descriptors: {
        5: "Bancas, estatuas y mesas en excelente estado. Senderos bien pavimentados y nivelados. Pérgolas funcionales.",
        4: "Mobiliario en buen estado con desgaste menor. Senderos transitables sin obstáculos.",
        3: "Algunos muebles deteriorados. Senderos con irregularidades menores (baldosas sueltas).",
        2: "Mobiliario roto o vandalizado. Senderos con huecos o adoquines levantados. Riesgo de tropiezo.",
        1: "Sin mobiliario funcional. Senderos intransitables. Charcos permanentes."
      }},
      { id: "limpieza_riego", name: "Limpieza y Riego", descriptors: {
        5: "Espacios limpios. Sin basura. Papeleras disponibles y vacías.",
        4: "Limpieza adecuada. Papeleras disponibles. Riego regular.",
        3: "Basura ocasional. Papeleras llenas. Riego irregular.",
        2: "Basura acumulada. Papeleras desbordadas o ausentes. Zonas secas por falta de riego.",
        1: "Espacio usado como basurero informal. Sin papeleras. Vegetación muerta por falta de riego."
      }},
      { id: "ilum_seg", name: "Iluminación y Seguridad", descriptors: {
        5: "Iluminación peatonal completa. Senderos delimitados.",
        4: "Iluminación adecuada en rutas principales.",
        3: "Iluminación parcial (zonas oscuras en senderos secundarios).",
        2: "Iluminación insuficiente. Zonas aisladas sin vigilancia.",
        1: "Sin iluminación funcional."
      }}
    ]
  },
  {
    id: "acceso", name: "Entrada / Salida / Acceso", icon: "🚪",
    dimensions: [
      { id: "estado_fisico", name: "Estado Físico de la Infraestructura", descriptors: {
        5: "Puertas, portones, torniquetes y barreras en excelente estado. Pisos antideslizantes. Techado adecuado.",
        4: "Infraestructura en buen estado. Desgaste menor en elementos de alto uso.",
        3: "Elementos funcionales con desgaste visible. Techado parcial. Pisos con irregularidades menores.",
        2: "Puertas/portones con dificultad de operación. Torniquetes averiados. Pisos resbalosos.",
        1: "Infraestructura severamente dañada o inoperable. Riesgo de caídas o atrapamiento."
      }},
      { id: "control_acceso", name: "Control de Acceso y Seguridad", descriptors: {
        5: "Sistema electrónico funcional (carnet). Personal de seguridad. Cámaras de seguridad visibles.",
        4: "Control funcional con fallas esporádicas. Seguridad en horarios principales.",
        3: "Control intermitente. Cobertura parcial. Cámaras con ángulos limitados.",
        2: "El control de acceso presenta fallas frecuentes. Seguridad insuficiente. Acceso sin verificación.",
        1: "Sin control de acceso funcional. Sin seguridad. Acceso libre e incontrolado."
      }},
      { id: "senalizacion_flujo", name: "Señalización y Flujo", descriptors: {
        5: "Señalización clara de entrada/salida vehicular y peatonal. Reductores funcionales.",
        4: "Señalización adecuada. Separación clara de flujos.",
        3: "Señalización parcial. Conflictos menores entre peatones y vehículos.",
        2: "Señalización confusa o ausente. Conflictos frecuentes peatón-vehículo.",
        1: "Sin señalización. Mezcla peligrosa de flujos. Riesgo de accidentes."
      }},
      { id: "accesibilidad", name: "Accesibilidad Universal", descriptors: {
        5: "Rampa con inclinación. Ancho para sillas de ruedas. Señalización inclusiva.",
        4: "Accesibilidad adecuada con detalles menores.",
        3: "Rampas presentes pero con pendiente pronunciada o desgaste. Accesibilidad parcial.",
        2: "Accesibilidad limitada. Rampas insuficientes. Barreras para personas con discapacidad.",
        1: "Sin consideraciones de accesibilidad. Imposible el acceso para movilidad reducida."
      }}
    ]
  },
  {
    id: "parqueadero", name: "Parqueadero", icon: "🅿️",
    dimensions: [
      { id: "superficie_dem", name: "Superficie y Demarcación", descriptors: {
        5: "Pavimento excelente. Demarcación completa y visible. Topes presentes.",
        4: "Pavimento en buen estado. Demarcación legible con desgaste menor.",
        3: "Pavimento con fisuras menores. Demarcación parcialmente borrada.",
        2: "Pavimento deteriorado con huecos. Demarcación ilegible. Charcos frecuentes.",
        1: "Pavimento severamente dañado. Sin demarcación. Riesgo de daño a vehículos."
      }},
      { id: "ilum_seg", name: "Iluminación y Seguridad", descriptors: {
        5: "Iluminación completa. Cámaras con cobertura total. Personal de vigilancia.",
        4: "Iluminación adecuada. Cámaras funcionales. Vigilancia regular.",
        3: "Iluminación parcial. Cámaras con cobertura limitada. Vigilancia intermitente.",
        2: "Iluminación deficiente. Pocas cámaras. Sin vigilancia regular.",
        1: "Sin iluminación nocturna. Sin cámaras ni vigilancia. Zona de alto riesgo."
      }},
      { id: "senal_circ", name: "Señalización y Circulación", descriptors: {
        5: "Señales de dirección, velocidad y pasos peatonales claros. Reductores de velocidad.",
        4: "Señalización funcional. Circulación organizada. Pasos peatonales visibles.",
        3: "Señalización parcial. Circulación funcional con confusión.",
        2: "Señalización insuficiente. Circulación confusa. Conflictos peatón-vehículo.",
        1: "Sin señalización. Circulación caótica. Riesgo elevado de accidentes."
      }},
         ]
  },
  {
    id: "bano", name: "Baño", icon: "🚻",
    dimensions: [
      { id: "aparatos", name: "Aparatos Sanitarios", descriptors: {
        5: "Sanitarios, lavamanos y orinales completos y funcionando. Sin fugas. Grifería en excelente estado.",
        4: "Aparatos funcionales con desgaste menor. Sin fugas significativas.",
        3: "Algunos aparatos intermitentes. Un aparato fuera de servicio.",
        2: "Varios aparatos fuera de servicio. Fugas visibles. Grifería deteriorada.",
        1: "Mayoría inoperativos. Fugas graves. Condiciones insalubres."
      }},
      { id: "limpieza_hig", name: "Limpieza e Higiene", descriptors: {
        5: "Impecable. Olor neutro. Pisos secos. Jabón, papel higiénico y papel manos llenos.",
        4: "Limpio. Olor aceptable. Suministros disponibles (>50%).",
        3: "Limpieza aceptable. Olor leve. Dispensadores parcialmente vacíos.",
        2: "Suciedad visible. Mal olor. Dispensadores vacíos. Pisos mojados.",
        1: "Condiciones antihigiénicas. Olor nauseabundo. Sin suministros. Plagas."
      }},
      { id: "infraestructura", name: "Infraestructura y Acabados", descriptors: {
        5: "Divisiones íntegras con cerraduras funcionales. Pisos y paredes en excelente estado. Ventilación adecuada (ventanas o 	sistema de extracción.",
        4: "Divisiones y cerraduras funcionales. Acabados en buen estado.",
        3: "Algunas cerraduras dañadas. Desgaste en paredes. Ventilación limitada o sin extractores.",
        2: "Divisiones dañadas. Varias cerraduras rotas. Humedad en paredes.",
        1: "Divisiones destruidas. Sin privacidad. Daño severo. Moho visible."
      }},
      { id: "accesibilidad", name: "Accesibilidad", descriptors: {
        5: "Baño accesible con barras de apoyo, espacio para silla de ruedas, lavamanos adaptado.",
        4: "Baño accesible funcional con detalles menores.",
        3: "Baño accesible con deficiencias (barras flojas, espacio reducido).",
        2: "Baño accesible inoperativo o con barreras significativas.",
        1: "Sin baño accesible disponible. Incumplimiento normativo."
      }}
    ]
  },
  {
    id: "pasillo", name: "Pasillo / Escalera / Área Común", icon: "🏛️",
    dimensions: [
      { id: "pisos", name: "Pisos y Superficies", descriptors: {
        5: "Pisos impecables y nivelados. Escaleras con cintas. Barandas firmes.",
        4: "Pisos en buen estado. Escaleras seguras. Barandas funcionales.",
        3: "Pisos con desgaste. Baldosas sueltas. Cintas antideslizantes desgastadas.",
        2: "Pisos resbalosos o con huecos. Escaleras sin cintas. Barandas flojas.",
        1: "Pisos peligrosos. Escaleras inseguras (escalones rotos, sin baranda)."
      }},
      { id: "ilum_vent", name: "Iluminación y Ventilación", descriptors: {
        5: "Iluminación uniforme. Ventilación adecuada. Luces de emergencia funcionales.",
        4: "Iluminación adecuada. Ventilación aceptable. Luces de emergencia presentes.",
        3: "Iluminación parcial (zonas oscuras). Ventilación limitada.",
        2: "Iluminación deficiente. Escaleras oscuras. Mala ventilación.",
        1: "Sin iluminación en zonas de tránsito. Sin ventilación. Sin luces de emergencia."
      }},
      { id: "senal_emerg", name: "Señalización y Emergencias", descriptors: {
        5: "Rutas de evacuación completas e iluminadas. Extintores presentes. Mapas de evacuación.",
        4: "Señalización de emergencia presente y legible.",
        3: "Señalización parcial.",
        2: "Señalización ausente o ilegible.",
        1: "Sin señalización de emergencia. Sin extintores. Rutas bloqueadas."
      }},
      { id: "ascensores", name: "Ascensores (si aplica)", descriptors: {
        5: "Ascensores funcionales y limpios. Botones en braille.",
        4: "Ascensores funcionales con desgaste menor.",
        3: "Ascensores con fallas ocasionales. Cabina desgastada. Tiempos largos.",
        2: "Ascensores frecuentemente fuera de servicio.",
        1: "Ascensores inoperativos. Sin alternativa accesible."
      }}
    ]
  },
  {
    id: "cafeteria", name: "Cafetería / Zona de Alimentación", icon: "🍽️",
    dimensions: [
      { id: "infraestructura", name: "Infraestructura y Mobiliario", descriptors: {
        5: "Mesas y sillas excelentes, suficientes para la demanda.",
        4: "Mobiliario en buen estado con desgaste menor. Distribución funcional.",
        3: "Mobiliario con desgaste visible. Espacio ajustado en horas pico.",
        2: "Mobiliario dañado. Hacinamiento. Pisos resbalosos o deteriorados.",
        1: "Mobiliario inutilizable. Infraestructura riesgosa. Inaceptable para consumo de alimentos."
      }},
      { id: "higiene", name: "Higiene y Manipulación de Alimentos", descriptors: {
        5: "Manipuladores con dotación completa. Superficies impecables. Bandejas y cubiertos higiénicos.",
        4: "Buenas prácticas observadas. Higiene adecuada. Bandejas y cubiertos disponibles.",
        3: "Manipulación aceptable con falencias menores. Superficies con desgaste. Bandejas y cubiertos en mal estado.",
        2: "Deficiencias notorias en manipulación. Superficies sucias. Alimentos sin protección. Bandejas y cubiertos sucios.",
        1: "Condiciones antihigiénicas graves. No hay bandejas ni cubiertos y/o no hay condiciones higiénicas."
      }},
      { id: "ventilacion_plagas", name: "Ventilación y Control de Plagas", descriptors: {
        5: "Ventilación adecuada sin olores. Climatización y temperatura confortable. No se observan plagas.",
        4: "Ventilación funcional. El aire acondicionado funciona (si aplica).",
        3: "Ventilación limitada (olores en horas pico). Temperatura con un poco de disconfort. Evidencia menor de insectos (telarañas, moscas).",
        2: "Ventilación deficiente (olores persistentes). El aire acondicionado no sirve o no hay sombraInsectos visibles.",
        1: "Sin ventilación. Presencia de roedores o infestación."
      }}
    ]
  },
  {
    id: "biblioteca", name: "Biblioteca / Zona de Estudio", icon: "📚",
    dimensions: [
      { id: "infraestructura", name: "Infraestructura y Mobiliario", descriptors: {
        5: "Mobiliario ergonómico excelente. Estantería sólida. Espacios diferenciados.",
        4: "Mobiliario en buen estado. Distribución funcional. Desgaste menor.",
        3: "Mobiliario funcional con desgaste. Estantería con deformaciones menores.",
        2: "Mobiliario deteriorado. Estanterías inestables. Insuficiente para la demanda.",
        1: "Mobiliario roto o inutilizable. Estantería con riesgo de colapso."
      }},
      { id: "tecnologia", name: "Tecnología y Conectividad", descriptors: {
        5: "Computadores funcionales. WiFi rápido. Tomas eléctricas suficientes.",
        4: "Tecnología funcional. Conectividad estable. Tomas adecuadas.",
        3: "Algunos computadores lentos. WiFi intermitente. Tomas insuficientes.",
        2: "Computadores obsoletos. WiFi deficiente. Pocas tomas funcionales.",
        1: "Sin computadores. Sin WiFi. Sin tomas eléctricas."
      }},
      { id: "ambiente", name: "Ambiente de Estudio", descriptors: {
        5: "Muy buena iluminación. Climatización confortable. Control acústico efectivo.",
        4: "Iluminación y climatización adecuadas. Ruido aceptable.",
        3: "Iluminación desigual. Climatización con variaciones. Ruido intermitente.",
        2: "Iluminación insuficiente. Climatización deficiente. Ruido constante.",
        1: "Condiciones ambientales inaceptables para estudio."
      }},
      { id: "senalizacion", name: "Señalización y Accesibilidad", descriptors: {
        5: "Señalización clara de secciones, normas y evacuación. Acceso universal. Horarios visibles.",
        4: "Señalización funcional. Accesibilidad adecuada con detalles menores.",
        3: "Señalización parcial. Accesibilidad limitada en algunas zonas.",
        2: "Señalización confusa o ausente. Barreras de accesibilidad significativas.",
        1: "Sin señalización. Sin accesibilidad para personas con discapacidad."
      }}
    ]
  },
  {
    id: "auditorio", name: "Auditorio / Sala de Eventos", icon: "🎭",
    dimensions: [
      { id: "estructura_asientos", name: "Estructura y Asientos", descriptors: {
        5: "Silletería excelente (tapizado íntegro y plegado funcional). Escenario sin daños.",
        4: "Silletería en buen estado con desgaste menor. Escenario funcional.",
        3: "Asientos con tapizado desgastado. Escenario con marcas de uso.",
        2: "Silletería dañada (asientos rotos, respaldos sueltos). Escenario con daños.",
        1: "Silletería inutilizable (>20%). Pisos peligrosos. Escenario inseguro."
      }},
      { id: "audiovisual", name: "Equipos Audiovisuales y Acústica", descriptors: {
        5: "Sonido claro. Pantalla alta resolución. Micrófonos funcionales. Acústica tratada.",
        4: "Equipos funcionales con calidad adecuada. Acústica aceptable.",
        3: "Equipos con deficiencias menores (micrófono con ruido, brillo reducido). Eco leve. Calidad de imagen reducida.",
        2: "Equipos con fallas significativas (sonido distorsionado). Acústica deficiente. Poca visibilidad de la pantalla.",
        1: "Equipos inoperativos. Acústica inaceptable. No apto para eventos."
      }},
      { id: "iluminacion", name: "Iluminación Escénica y General", descriptors: {
        5: "Iluminación escénica completa. Luces de emergencia. Control centralizado.",
        4: "Iluminación funcional con regulación. Luces de emergencia presentes.",
        3: "Iluminación general sin regulación.",
        2: "Iluminación insuficiente o sin regulación. Sin escénica.",
        1: "Iluminación deficiente que impide eventos. Sin luces de emergencia."
      }},
      { id: "clima_servicios", name: "Climatización y Servicios", descriptors: {
        5: "Climatización silenciosa para aforo completo. Baños cercanos. Accesibilidad completa.",
        4: "Climatización adecuada. Servicios disponibles. Accesibilidad funcional.",
        3: "Climatización insuficiente. Baños distantes.",
        2: "Climatización deficiente o ruidosa. Servicios limitados.",
        1: "Sin climatización. Sin servicios. Sin accesibilidad."
      }}
    ]
  }
];

const CLASSIFICATIONS = [
  { min: 4.5, max: 5.0, label: "Excelente", color: "#22c55e", emoji: "🟢", action: "Mantener mantenimiento preventivo." },
  { min: 3.5, max: 4.49, label: "Bueno", color: "#3b82f6", emoji: "🔵", action: "Programar mantenimiento preventivo." },
  { min: 2.5, max: 3.49, label: "Aceptable", color: "#eab308", emoji: "🟡", action: "Mantenimiento correctivo (1-3 meses)." },
  { min: 1.5, max: 2.49, label: "Deficiente", color: "#f97316", emoji: "🟠", action: "Intervención prioritaria (1-4 semanas)." },
  { min: 1.0, max: 1.49, label: "Crítico", color: "#ef4444", emoji: "🔴", action: "Intervención inmediata (1-7 días)." }
];

function getClassification(score) {
  if (score === null || isNaN(score)) return null;
  for (const c of CLASSIFICATIONS) {
    if (score >= c.min && score <= c.max) return c;
  }
  return CLASSIFICATIONS[CLASSIFICATIONS.length - 1];
}
